// GENERATED by `cargo run --bin extract` — do not edit by hand.
// Source: stm32-metapac chip STM32C5A3ZGT6 (STM32C5 Series family); DMA from stm32-data chip JSON.

use crate::mcu_raw::{RawMcuData, RawPeripheral, RawPin, RawDmaLeg, DmaPoolDef};

pub static RAW: RawMcuData = RawMcuData {
    name: "STM32C5A3ZGT6",
    family: "STM32C5 Series",
    peripherals: &[
        RawPeripheral { name: "ADC1", address: 0x42028000, block: None, pins: &[
            RawPin { pin: "PA0", signal: "IN0", af: None },
            RawPin { pin: "PA1", signal: "IN1", af: None },
            RawPin { pin: "PA2", signal: "IN2", af: None },
            RawPin { pin: "PA3", signal: "IN3", af: None },
            RawPin { pin: "PA4", signal: "IN4", af: None },
            RawPin { pin: "PA5", signal: "IN5", af: None },
            RawPin { pin: "PA6", signal: "IN6", af: None },
            RawPin { pin: "PA7", signal: "IN7", af: None },
            RawPin { pin: "PC0", signal: "IN8", af: None },
            RawPin { pin: "PC1", signal: "IN9", af: None },
            RawPin { pin: "PC2", signal: "IN10", af: None },
            RawPin { pin: "PC3", signal: "IN11", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "GLOBAL", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "ADC12_COMMON", address: 0x42028300, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "ADC2", address: 0x42028100, block: None, pins: &[
            RawPin { pin: "PA0", signal: "IN0", af: None },
            RawPin { pin: "PA1", signal: "IN1", af: None },
            RawPin { pin: "PA2", signal: "IN2", af: None },
            RawPin { pin: "PA3", signal: "IN3", af: None },
            RawPin { pin: "PB0", signal: "IN6", af: None },
            RawPin { pin: "PB1", signal: "IN7", af: None },
            RawPin { pin: "PB2", signal: "IN8", af: None },
            RawPin { pin: "PC1", signal: "IN9", af: None },
            RawPin { pin: "PC2", signal: "IN10", af: None },
            RawPin { pin: "PC3", signal: "IN11", af: None },
            RawPin { pin: "PC4", signal: "IN4", af: None },
            RawPin { pin: "PC5", signal: "IN5", af: None },
            RawPin { pin: "PH4", signal: "IN12", af: None },
            RawPin { pin: "PH5", signal: "IN13", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "GLOBAL", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "ADC3", address: 0x4202d800, block: None, pins: &[
            RawPin { pin: "PB0", signal: "IN0", af: None },
            RawPin { pin: "PB1", signal: "IN1", af: None },
            RawPin { pin: "PB2", signal: "IN2", af: None },
            RawPin { pin: "PE10", signal: "IN6", af: None },
            RawPin { pin: "PE11", signal: "IN7", af: None },
            RawPin { pin: "PE12", signal: "IN8", af: None },
            RawPin { pin: "PE13", signal: "IN9", af: None },
            RawPin { pin: "PE14", signal: "IN10", af: None },
            RawPin { pin: "PE15", signal: "IN11", af: None },
            RawPin { pin: "PE7", signal: "IN3", af: None },
            RawPin { pin: "PE8", signal: "IN4", af: None },
            RawPin { pin: "PE9", signal: "IN5", af: None },
            RawPin { pin: "PH4", signal: "IN12", af: None },
            RawPin { pin: "PH5", signal: "IN13", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "GLOBAL", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "ADC3_COMMON", address: 0x4202db00, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "AES", address: 0x420c0000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "IN", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "OUT", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "CCB", address: 0x420c7c00, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "COMP1", address: 0x40004000, block: None, pins: &[
            RawPin { pin: "PA0", signal: "INP1", af: None },
            RawPin { pin: "PA13(JTMS/SWDIO)", signal: "OUT", af: None },
            RawPin { pin: "PA3", signal: "OUT", af: None },
            RawPin { pin: "PA5", signal: "INM3", af: None },
            RawPin { pin: "PB0", signal: "INP2", af: None },
            RawPin { pin: "PB1", signal: "INM2", af: None },
            RawPin { pin: "PB1", signal: "OUT", af: None },
            RawPin { pin: "PB2", signal: "INP3", af: None },
            RawPin { pin: "PC4", signal: "INM1", af: None },
            RawPin { pin: "PC5", signal: "OUT", af: None },
            RawPin { pin: "PE12", signal: "OUT", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "CORDIC", address: 0x40023800, block: Some("CORDIC"), pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RD", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "WR", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "CRC", address: 0x40023000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "CRS", address: 0x40006000, block: None, pins: &[
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "SYNC", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "DAC1", address: 0x42028400, block: None, pins: &[
            RawPin { pin: "PA4", signal: "OUT1", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "DBGMCU", address: 0x44024000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "ETH1", address: 0x40028000, block: None, pins: &[
            RawPin { pin: "PA0", signal: "CRS", af: None },
            RawPin { pin: "PA1", signal: "REF_CLK", af: None },
            RawPin { pin: "PA1", signal: "RX_CLK", af: None },
            RawPin { pin: "PA10", signal: "CLK", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "PHY_INTN", af: None },
            RawPin { pin: "PA2", signal: "MDIO", af: None },
            RawPin { pin: "PA3", signal: "COL", af: None },
            RawPin { pin: "PA5", signal: "TX_EN", af: None },
            RawPin { pin: "PA7", signal: "CRS_DV", af: None },
            RawPin { pin: "PA7", signal: "RX_DV", af: None },
            RawPin { pin: "PA9", signal: "TX_ER", af: None },
            RawPin { pin: "PB0", signal: "RXD2", af: None },
            RawPin { pin: "PB1", signal: "RXD3", af: None },
            RawPin { pin: "PB10", signal: "RX_ER", af: None },
            RawPin { pin: "PB12", signal: "TXD0", af: None },
            RawPin { pin: "PB13", signal: "TX_EN", af: None },
            RawPin { pin: "PB15", signal: "TXD1", af: None },
            RawPin { pin: "PB2", signal: "RXD0", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "MDC", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "MDIO", af: None },
            RawPin { pin: "PB5", signal: "PPS_OUT", af: None },
            RawPin { pin: "PB6", signal: "TX_ER", af: None },
            RawPin { pin: "PB8", signal: "TXD3", af: None },
            RawPin { pin: "PC1", signal: "MDC", af: None },
            RawPin { pin: "PC10", signal: "TXD0", af: None },
            RawPin { pin: "PC12", signal: "PPS_OUT", af: None },
            RawPin { pin: "PC2", signal: "TXD2", af: None },
            RawPin { pin: "PC3", signal: "TX_CLK", af: None },
            RawPin { pin: "PC4", signal: "RXD0", af: None },
            RawPin { pin: "PC5", signal: "RXD1", af: None },
            RawPin { pin: "PD1", signal: "CRS_DV", af: None },
            RawPin { pin: "PD1", signal: "RX_DV", af: None },
            RawPin { pin: "PD10", signal: "CRS", af: None },
            RawPin { pin: "PD11", signal: "PTP_AUX_TS", af: None },
            RawPin { pin: "PD4", signal: "CLK", af: None },
            RawPin { pin: "PD5", signal: "CRS", af: None },
            RawPin { pin: "PD8", signal: "RXD0", af: None },
            RawPin { pin: "PE12", signal: "MDIO", af: None },
            RawPin { pin: "PE2", signal: "TXD3", af: None },
            RawPin { pin: "PE4", signal: "RXD0", af: None },
            RawPin { pin: "PE5", signal: "RXD1", af: None },
            RawPin { pin: "PF15", signal: "CLK", af: None },
            RawPin { pin: "PF8", signal: "TX_ER", af: None },
            RawPin { pin: "PF9", signal: "MDC", af: None },
            RawPin { pin: "PG11", signal: "TX_EN", af: None },
            RawPin { pin: "PG12", signal: "TXD1", af: None },
            RawPin { pin: "PG13", signal: "TXD0", af: None },
            RawPin { pin: "PG14", signal: "TXD1", af: None },
            RawPin { pin: "PG3", signal: "RX_ER", af: None },
            RawPin { pin: "PG8", signal: "PPS_OUT", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "EXTI", address: 0x44022000, block: Some("EXTI"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FDCAN1", address: 0x4000a400, block: None, pins: &[
            RawPin { pin: "PA11", signal: "RX", af: None },
            RawPin { pin: "PA12", signal: "TX", af: None },
            RawPin { pin: "PB7", signal: "TX", af: None },
            RawPin { pin: "PB8", signal: "RX", af: None },
            RawPin { pin: "PB9", signal: "TX", af: None },
            RawPin { pin: "PC13", signal: "TX", af: None },
            RawPin { pin: "PC14-OSC32_IN(OSC32_IN)", signal: "RX", af: None },
            RawPin { pin: "PD0", signal: "RX", af: None },
            RawPin { pin: "PD1", signal: "TX", af: None },
            RawPin { pin: "PD5", signal: "TX", af: None },
            RawPin { pin: "PE0", signal: "RX", af: None },
            RawPin { pin: "PE1", signal: "TX", af: None },
            RawPin { pin: "PH2-BOOT0", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FDCAN2", address: 0x4000a800, block: None, pins: &[
            RawPin { pin: "PA10", signal: "TX", af: None },
            RawPin { pin: "PB12", signal: "RX", af: None },
            RawPin { pin: "PB13", signal: "TX", af: None },
            RawPin { pin: "PB5", signal: "RX", af: None },
            RawPin { pin: "PB6", signal: "TX", af: None },
            RawPin { pin: "PD9", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FDCANRAM", address: 0x4000ac00, block: Some("FDCANRAM"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FDCANRAM1", address: 0x4000ac00, block: Some("FDCANRAM"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FDCANRAM2", address: 0x4000af50, block: Some("FDCANRAM"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "FLASH", address: 0x40022000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOA", address: 0x42020000, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOB", address: 0x42020400, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOC", address: 0x42020800, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOD", address: 0x42020c00, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOE", address: 0x42021000, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOF", address: 0x42021400, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOG", address: 0x42021800, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "GPIOH", address: 0x42021c00, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "HASH", address: 0x420c0400, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "IN", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "I2C1", address: 0x40005400, block: None, pins: &[
            RawPin { pin: "PA8", signal: "SCL", af: None },
            RawPin { pin: "PA9", signal: "SMBA", af: None },
            RawPin { pin: "PB5", signal: "SMBA", af: None },
            RawPin { pin: "PB6", signal: "SCL", af: None },
            RawPin { pin: "PB7", signal: "SDA", af: None },
            RawPin { pin: "PB8", signal: "SCL", af: None },
            RawPin { pin: "PB9", signal: "SDA", af: None },
            RawPin { pin: "PC9", signal: "SDA", af: None },
            RawPin { pin: "PH0-OSC_IN(PH0)", signal: "SDA", af: None },
            RawPin { pin: "PH1-OSC_OUT(PH1)", signal: "SCL", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "I2C2", address: 0x40005800, block: None, pins: &[
            RawPin { pin: "PA11", signal: "SCL", af: None },
            RawPin { pin: "PA12", signal: "SDA", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "SMBA", af: None },
            RawPin { pin: "PB10", signal: "SCL", af: None },
            RawPin { pin: "PB12", signal: "SDA", af: None },
            RawPin { pin: "PB13", signal: "SMBA", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "SCL", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "SDA", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "SDA", af: None },
            RawPin { pin: "PF0", signal: "SDA", af: None },
            RawPin { pin: "PF1", signal: "SCL", af: None },
            RawPin { pin: "PF2", signal: "SMBA", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "I3C1", address: 0x40005c00, block: None, pins: &[
            RawPin { pin: "PA8", signal: "SDA", af: None },
            RawPin { pin: "PA9", signal: "SCL", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "SCL", af: None },
            RawPin { pin: "PB5", signal: "SDA", af: None },
            RawPin { pin: "PB6", signal: "SCL", af: None },
            RawPin { pin: "PB7", signal: "SDA", af: None },
            RawPin { pin: "PB8", signal: "SCL", af: None },
            RawPin { pin: "PB9", signal: "SDA", af: None },
            RawPin { pin: "PC10", signal: "SCL", af: None },
            RawPin { pin: "PC11", signal: "SDA", af: None },
            RawPin { pin: "PD12", signal: "SCL", af: None },
            RawPin { pin: "PD13", signal: "SDA", af: None },
            RawPin { pin: "PF15", signal: "SDA", af: None },
            RawPin { pin: "PF5", signal: "SCL", af: None },
            RawPin { pin: "PG6", signal: "SDA", af: None },
            RawPin { pin: "PG7", signal: "SCL", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RS", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TC", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "ICACHE", address: 0x40030400, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "IWDG", address: 0x40003000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "LPDMA1", address: 0x40020000, block: Some("LPDMA"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "LPDMA2", address: 0x40021000, block: Some("LPDMA"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "LPTIM1", address: 0x44004400, block: None, pins: &[
            RawPin { pin: "PA1", signal: "IN1", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "ETR", af: None },
            RawPin { pin: "PA2", signal: "IN2", af: None },
            RawPin { pin: "PB10", signal: "IN1", af: None },
            RawPin { pin: "PB13", signal: "CH1", af: None },
            RawPin { pin: "PB2", signal: "CH1", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "CH2", af: None },
            RawPin { pin: "PD10", signal: "CH2", af: None },
            RawPin { pin: "PD11", signal: "IN2", af: None },
            RawPin { pin: "PD12", signal: "IN1", af: None },
            RawPin { pin: "PD13", signal: "CH1", af: None },
            RawPin { pin: "PE0", signal: "ETR", af: None },
            RawPin { pin: "PE1", signal: "IN2", af: None },
            RawPin { pin: "PE2", signal: "IN2", af: None },
            RawPin { pin: "PG11", signal: "IN2", af: None },
            RawPin { pin: "PG12", signal: "IN1", af: None },
            RawPin { pin: "PG13", signal: "CH1", af: None },
            RawPin { pin: "PG14", signal: "CH2", af: None },
            RawPin { pin: "PG14", signal: "ETR", af: None },
            RawPin { pin: "PH2-BOOT0", signal: "IN2", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "IC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "IC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UE", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "LPUART1", address: 0x44002400, block: None, pins: &[
            RawPin { pin: "PA10", signal: "RX", af: None },
            RawPin { pin: "PA11", signal: "CTS", af: None },
            RawPin { pin: "PA12", signal: "RTS", af: None },
            RawPin { pin: "PA2", signal: "RX", af: None },
            RawPin { pin: "PA3", signal: "TX", af: None },
            RawPin { pin: "PA6", signal: "RTS", af: None },
            RawPin { pin: "PA7", signal: "CTS", af: None },
            RawPin { pin: "PA9", signal: "TX", af: None },
            RawPin { pin: "PB13", signal: "RX", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "TX", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "CTS", af: None },
            RawPin { pin: "PB5", signal: "RTS", af: None },
            RawPin { pin: "PB6", signal: "TX", af: None },
            RawPin { pin: "PB7", signal: "RX", af: None },
            RawPin { pin: "PC3", signal: "TX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "PKA", address: 0x420c2000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "PWR", address: 0x44020800, block: None, pins: &[
            RawPin { pin: "PA0", signal: "WKUP1", af: None },
            RawPin { pin: "PA2", signal: "WKUP2", af: None },
            RawPin { pin: "PB7", signal: "WKUP5", af: None },
            RawPin { pin: "PC1", signal: "WKUP6", af: None },
            RawPin { pin: "PC13", signal: "WKUP4", af: None },
            RawPin { pin: "PC2", signal: "CSLEEP", af: None },
            RawPin { pin: "PC3", signal: "CSTOP", af: None },
            RawPin { pin: "PD2", signal: "WKUP7", af: None },
            RawPin { pin: "PE6", signal: "WKUP3", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RAMCFG", address: 0x40026000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RAMCFG_SRAM1", address: 0x40026000, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RAMCFG_SRAM2", address: 0x40026040, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RCC", address: 0x44020c00, block: Some("RCC"), pins: &[
            RawPin { pin: "PA8", signal: "MCO1", af: None },
            RawPin { pin: "PA9", signal: "MCO2", af: None },
            RawPin { pin: "PB2", signal: "LSCO", af: None },
            RawPin { pin: "PC14-OSC32_IN(OSC32_IN)", signal: "OSC32_IN", af: None },
            RawPin { pin: "PC15-OSC32_OUT(OSC32_OUT)", signal: "OSC32_OUT", af: None },
            RawPin { pin: "PC9", signal: "AUDIOCLK", af: None },
            RawPin { pin: "PC9", signal: "MCO2", af: None },
            RawPin { pin: "PD10", signal: "MCO2", af: None },
            RawPin { pin: "PH0-OSC_IN(PH0)", signal: "OSC_IN", af: None },
            RawPin { pin: "PH1-OSC_OUT(PH1)", signal: "OSC_OUT", af: None },
            RawPin { pin: "PH2-BOOT0", signal: "MCO1", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RNG", address: 0x420c0800, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "RTC", address: 0x44007800, block: None, pins: &[
            RawPin { pin: "PB15", signal: "REFIN", af: None },
            RawPin { pin: "PB2", signal: "OUT2", af: None },
            RawPin { pin: "PC13", signal: "OUT1", af: None },
            RawPin { pin: "PC13", signal: "TS", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "SAES", address: 0x420c0c00, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "IN", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "OUT", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "SPI1", address: 0x40013000, block: None, pins: &[
            RawPin { pin: "PA15(JTDI)", signal: "I2S_WS", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "NSS", af: None },
            RawPin { pin: "PA4", signal: "I2S_WS", af: None },
            RawPin { pin: "PA4", signal: "NSS", af: None },
            RawPin { pin: "PA5", signal: "I2S_CK", af: None },
            RawPin { pin: "PA5", signal: "SCK", af: None },
            RawPin { pin: "PA6", signal: "I2S_SDI", af: None },
            RawPin { pin: "PA6", signal: "MISO", af: None },
            RawPin { pin: "PA7", signal: "I2S_SDO", af: None },
            RawPin { pin: "PA7", signal: "MOSI", af: None },
            RawPin { pin: "PA8", signal: "RDY", af: None },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB15", signal: "MOSI", af: None },
            RawPin { pin: "PB2", signal: "RDY", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "I2S_CK", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "SCK", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "I2S_SDI", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "MISO", af: None },
            RawPin { pin: "PB5", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB5", signal: "MOSI", af: None },
            RawPin { pin: "PC4", signal: "I2S_MCK", af: None },
            RawPin { pin: "PD7", signal: "I2S_SDO", af: None },
            RawPin { pin: "PD7", signal: "MOSI", af: None },
            RawPin { pin: "PE11", signal: "RDY", af: None },
            RawPin { pin: "PG10", signal: "I2S_WS", af: None },
            RawPin { pin: "PG10", signal: "NSS", af: None },
            RawPin { pin: "PG11", signal: "I2S_CK", af: None },
            RawPin { pin: "PG11", signal: "SCK", af: None },
            RawPin { pin: "PG6", signal: "RDY", af: None },
            RawPin { pin: "PG9", signal: "I2S_SDI", af: None },
            RawPin { pin: "PG9", signal: "MISO", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "SPI2", address: 0x40003800, block: None, pins: &[
            RawPin { pin: "PA0", signal: "I2S_WS", af: None },
            RawPin { pin: "PA0", signal: "NSS", af: None },
            RawPin { pin: "PA0", signal: "RDY", af: None },
            RawPin { pin: "PA11", signal: "I2S_WS", af: None },
            RawPin { pin: "PA11", signal: "NSS", af: None },
            RawPin { pin: "PA12", signal: "I2S_CK", af: None },
            RawPin { pin: "PA12", signal: "SCK", af: None },
            RawPin { pin: "PA3", signal: "I2S_WS", af: None },
            RawPin { pin: "PA3", signal: "NSS", af: None },
            RawPin { pin: "PA5", signal: "I2S_CK", af: None },
            RawPin { pin: "PA5", signal: "SCK", af: None },
            RawPin { pin: "PA7", signal: "I2S_SDI", af: None },
            RawPin { pin: "PA7", signal: "MISO", af: None },
            RawPin { pin: "PA8", signal: "I2S_SDO", af: None },
            RawPin { pin: "PA8", signal: "MOSI", af: None },
            RawPin { pin: "PA9", signal: "I2S_CK", af: None },
            RawPin { pin: "PA9", signal: "SCK", af: None },
            RawPin { pin: "PB1", signal: "I2S_WS", af: None },
            RawPin { pin: "PB1", signal: "NSS", af: None },
            RawPin { pin: "PB10", signal: "I2S_CK", af: None },
            RawPin { pin: "PB10", signal: "SCK", af: None },
            RawPin { pin: "PB12", signal: "I2S_WS", af: None },
            RawPin { pin: "PB12", signal: "NSS", af: None },
            RawPin { pin: "PB13", signal: "I2S_CK", af: None },
            RawPin { pin: "PB13", signal: "SCK", af: None },
            RawPin { pin: "PB14", signal: "I2S_SDI", af: None },
            RawPin { pin: "PB14", signal: "MISO", af: None },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB15", signal: "MOSI", af: None },
            RawPin { pin: "PB2", signal: "I2S_CK", af: None },
            RawPin { pin: "PB2", signal: "SCK", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "I2S_WS", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "NSS", af: None },
            RawPin { pin: "PB9", signal: "I2S_WS", af: None },
            RawPin { pin: "PB9", signal: "NSS", af: None },
            RawPin { pin: "PC0", signal: "RDY", af: None },
            RawPin { pin: "PC1", signal: "I2S_SDO", af: None },
            RawPin { pin: "PC1", signal: "MOSI", af: None },
            RawPin { pin: "PC2", signal: "I2S_SDI", af: None },
            RawPin { pin: "PC2", signal: "MISO", af: None },
            RawPin { pin: "PC3", signal: "I2S_SDO", af: None },
            RawPin { pin: "PC3", signal: "MOSI", af: None },
            RawPin { pin: "PC6", signal: "I2S_MCK", af: None },
            RawPin { pin: "PD3", signal: "I2S_CK", af: None },
            RawPin { pin: "PD3", signal: "SCK", af: None },
            RawPin { pin: "PD5", signal: "RDY", af: None },
            RawPin { pin: "PG1", signal: "I2S_SDO", af: None },
            RawPin { pin: "PG1", signal: "MOSI", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "SPI3", address: 0x40003c00, block: None, pins: &[
            RawPin { pin: "PA0", signal: "RDY", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "I2S_WS", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "NSS", af: None },
            RawPin { pin: "PA3", signal: "I2S_SDO", af: None },
            RawPin { pin: "PA3", signal: "MOSI", af: None },
            RawPin { pin: "PA4", signal: "I2S_SDO", af: None },
            RawPin { pin: "PA4", signal: "I2S_WS", af: None },
            RawPin { pin: "PA4", signal: "MOSI", af: None },
            RawPin { pin: "PA4", signal: "NSS", af: None },
            RawPin { pin: "PB0", signal: "I2S_SDI", af: None },
            RawPin { pin: "PB0", signal: "MISO", af: None },
            RawPin { pin: "PB1", signal: "I2S_CK", af: None },
            RawPin { pin: "PB1", signal: "SCK", af: None },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB15", signal: "MOSI", af: None },
            RawPin { pin: "PB2", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB2", signal: "MOSI", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "I2S_CK", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "SCK", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "I2S_SDI", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "MISO", af: None },
            RawPin { pin: "PB5", signal: "I2S_SDO", af: None },
            RawPin { pin: "PB5", signal: "MOSI", af: None },
            RawPin { pin: "PB6", signal: "I2S_SDI", af: None },
            RawPin { pin: "PB6", signal: "MISO", af: None },
            RawPin { pin: "PB7", signal: "I2S_CK", af: None },
            RawPin { pin: "PB7", signal: "SCK", af: None },
            RawPin { pin: "PB8", signal: "I2S_WS", af: None },
            RawPin { pin: "PB8", signal: "NSS", af: None },
            RawPin { pin: "PB9", signal: "I2S_CK", af: None },
            RawPin { pin: "PB9", signal: "SCK", af: None },
            RawPin { pin: "PC10", signal: "I2S_CK", af: None },
            RawPin { pin: "PC10", signal: "SCK", af: None },
            RawPin { pin: "PC11", signal: "I2S_SDI", af: None },
            RawPin { pin: "PC11", signal: "MISO", af: None },
            RawPin { pin: "PC12", signal: "I2S_SDO", af: None },
            RawPin { pin: "PC12", signal: "MOSI", af: None },
            RawPin { pin: "PC7", signal: "I2S_MCK", af: None },
            RawPin { pin: "PD6", signal: "I2S_SDO", af: None },
            RawPin { pin: "PD6", signal: "MOSI", af: None },
            RawPin { pin: "PD7", signal: "I2S_SDI", af: None },
            RawPin { pin: "PD7", signal: "MISO", af: None },
            RawPin { pin: "PE0", signal: "RDY", af: None },
            RawPin { pin: "PE2", signal: "I2S_CK", af: None },
            RawPin { pin: "PE2", signal: "SCK", af: None },
            RawPin { pin: "PE4", signal: "I2S_WS", af: None },
            RawPin { pin: "PE4", signal: "NSS", af: None },
            RawPin { pin: "PE5", signal: "I2S_SDI", af: None },
            RawPin { pin: "PE5", signal: "MISO", af: None },
            RawPin { pin: "PE6", signal: "I2S_SDO", af: None },
            RawPin { pin: "PE6", signal: "MOSI", af: None },
            RawPin { pin: "PG8", signal: "I2S_SDO", af: None },
            RawPin { pin: "PG8", signal: "MOSI", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "SYSCFG", address: 0x44000400, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "TAMP", address: 0x44007c00, block: None, pins: &[
            RawPin { pin: "PA0", signal: "IN2", af: None },
            RawPin { pin: "PA1", signal: "IN3", af: None },
            RawPin { pin: "PA2", signal: "IN3", af: None },
            RawPin { pin: "PC1", signal: "IN2", af: None },
            RawPin { pin: "PC13", signal: "IN1", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "TIM1", address: 0x40012c00, block: Some("TIM_ADV"), pins: &[
            RawPin { pin: "PA10", signal: "CH3", af: None },
            RawPin { pin: "PA11", signal: "CH4", af: None },
            RawPin { pin: "PA12", signal: "ETR", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "CH2N", af: None },
            RawPin { pin: "PA5", signal: "CH3", af: None },
            RawPin { pin: "PA6", signal: "BKIN", af: None },
            RawPin { pin: "PA7", signal: "CH1N", af: None },
            RawPin { pin: "PA8", signal: "CH1", af: None },
            RawPin { pin: "PA9", signal: "CH2", af: None },
            RawPin { pin: "PB0", signal: "CH2N", af: None },
            RawPin { pin: "PB1", signal: "CH3N", af: None },
            RawPin { pin: "PB12", signal: "BKIN", af: None },
            RawPin { pin: "PB13", signal: "CH1N", af: None },
            RawPin { pin: "PB14", signal: "CH2N", af: None },
            RawPin { pin: "PB15", signal: "CH3N", af: None },
            RawPin { pin: "PC5", signal: "CH4N", af: None },
            RawPin { pin: "PD5", signal: "CH4N", af: None },
            RawPin { pin: "PE10", signal: "CH2N", af: None },
            RawPin { pin: "PE11", signal: "CH2", af: None },
            RawPin { pin: "PE12", signal: "CH3N", af: None },
            RawPin { pin: "PE13", signal: "CH3", af: None },
            RawPin { pin: "PE14", signal: "CH4", af: None },
            RawPin { pin: "PE15", signal: "BKIN", af: None },
            RawPin { pin: "PE15", signal: "CH4N", af: None },
            RawPin { pin: "PE6", signal: "BKIN2", af: None },
            RawPin { pin: "PE7", signal: "ETR", af: None },
            RawPin { pin: "PE8", signal: "CH1N", af: None },
            RawPin { pin: "PE9", signal: "CH1", af: None },
            RawPin { pin: "PG4", signal: "BKIN2", af: None },
            RawPin { pin: "PG5", signal: "ETR", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "COM", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM12", address: 0x40001800, block: Some("TIM_2CH"), pins: &[
            RawPin { pin: "PB14", signal: "CH1", af: None },
            RawPin { pin: "PB15", signal: "CH2", af: None },
            RawPin { pin: "PC14-OSC32_IN(OSC32_IN)", signal: "CH1", af: None },
            RawPin { pin: "PC15-OSC32_OUT(OSC32_OUT)", signal: "CH2", af: None },
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "TIM15", address: 0x40014000, block: Some("TIM_2CH_CMP"), pins: &[
            RawPin { pin: "PA0", signal: "BKIN", af: None },
            RawPin { pin: "PA1", signal: "CH1N", af: None },
            RawPin { pin: "PA2", signal: "CH1", af: None },
            RawPin { pin: "PA3", signal: "CH2", af: None },
            RawPin { pin: "PA7", signal: "CH1", af: None },
            RawPin { pin: "PA8", signal: "CH2", af: None },
            RawPin { pin: "PA9", signal: "CH1N", af: None },
            RawPin { pin: "PC12", signal: "CH1", af: None },
            RawPin { pin: "PD2", signal: "BKIN", af: None },
            RawPin { pin: "PE3", signal: "BKIN", af: None },
            RawPin { pin: "PE4", signal: "CH1N", af: None },
            RawPin { pin: "PE5", signal: "CH1", af: None },
            RawPin { pin: "PE6", signal: "CH2", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "COM", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM16", address: 0x40014400, block: Some("TIM_1CH_CMP"), pins: &[
            RawPin { pin: "PB4(NJTRST)", signal: "BKIN", af: None },
            RawPin { pin: "PB6", signal: "CH1N", af: None },
            RawPin { pin: "PB7", signal: "CH1", af: None },
            RawPin { pin: "PC0", signal: "BKIN", af: None },
            RawPin { pin: "PC4", signal: "CH1", af: None },
            RawPin { pin: "PC5", signal: "CH1N", af: None },
            RawPin { pin: "PF10", signal: "BKIN", af: None },
            RawPin { pin: "PF6", signal: "CH1", af: None },
            RawPin { pin: "PF8", signal: "CH1N", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM17", address: 0x40014800, block: Some("TIM_1CH_CMP"), pins: &[
            RawPin { pin: "PB5", signal: "BKIN", af: None },
            RawPin { pin: "PB7", signal: "CH1N", af: None },
            RawPin { pin: "PB8", signal: "CH1", af: None },
            RawPin { pin: "PC2", signal: "CH1", af: None },
            RawPin { pin: "PF7", signal: "CH1", af: None },
            RawPin { pin: "PF9", signal: "CH1N", af: None },
            RawPin { pin: "PG6", signal: "BKIN", af: None },
            RawPin { pin: "PH2-BOOT0", signal: "CH1N", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM2", address: 0x40000000, block: Some("TIM_GP32"), pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: None },
            RawPin { pin: "PA0", signal: "ETR", af: None },
            RawPin { pin: "PA1", signal: "CH2", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "CH1", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "ETR", af: None },
            RawPin { pin: "PA2", signal: "CH3", af: None },
            RawPin { pin: "PA3", signal: "CH4", af: None },
            RawPin { pin: "PA5", signal: "CH1", af: None },
            RawPin { pin: "PA5", signal: "ETR", af: None },
            RawPin { pin: "PA8", signal: "CH4", af: None },
            RawPin { pin: "PB10", signal: "CH3", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "CH2", af: None },
            RawPin { pin: "PC4", signal: "CH4", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM3", address: 0x40000400, block: Some("TIM_GP16"), pins: &[
            RawPin { pin: "PA3", signal: "CH3", af: None },
            RawPin { pin: "PA4", signal: "CH4", af: None },
            RawPin { pin: "PA6", signal: "CH1", af: None },
            RawPin { pin: "PA7", signal: "CH2", af: None },
            RawPin { pin: "PB0", signal: "CH3", af: None },
            RawPin { pin: "PB1", signal: "CH4", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "CH1", af: None },
            RawPin { pin: "PB5", signal: "CH2", af: None },
            RawPin { pin: "PC6", signal: "CH1", af: None },
            RawPin { pin: "PC7", signal: "CH2", af: None },
            RawPin { pin: "PC8", signal: "CH3", af: None },
            RawPin { pin: "PC9", signal: "CH4", af: None },
            RawPin { pin: "PD2", signal: "ETR", af: None },
            RawPin { pin: "PF14", signal: "ETR", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM4", address: 0x40000800, block: Some("TIM_GP16"), pins: &[
            RawPin { pin: "PB6", signal: "CH1", af: None },
            RawPin { pin: "PB7", signal: "CH2", af: None },
            RawPin { pin: "PB8", signal: "CH3", af: None },
            RawPin { pin: "PB9", signal: "CH4", af: None },
            RawPin { pin: "PC2", signal: "CH4", af: None },
            RawPin { pin: "PD12", signal: "CH1", af: None },
            RawPin { pin: "PD13", signal: "CH2", af: None },
            RawPin { pin: "PD14", signal: "CH3", af: None },
            RawPin { pin: "PD15", signal: "CH4", af: None },
            RawPin { pin: "PE0", signal: "ETR", af: None },
            RawPin { pin: "PF15", signal: "ETR", af: None },
            RawPin { pin: "PG0", signal: "CH1", af: None },
            RawPin { pin: "PG1", signal: "CH2", af: None },
            RawPin { pin: "PG2", signal: "CH3", af: None },
            RawPin { pin: "PG3", signal: "CH4", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM5", address: 0x40000c00, block: Some("TIM_GP32"), pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: None },
            RawPin { pin: "PA1", signal: "CH2", af: None },
            RawPin { pin: "PA2", signal: "CH3", af: None },
            RawPin { pin: "PA3", signal: "CH4", af: None },
            RawPin { pin: "PA4", signal: "ETR", af: None },
            RawPin { pin: "PA8", signal: "CH4", af: None },
            RawPin { pin: "PA9", signal: "ETR", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "CH3", af: None },
            RawPin { pin: "PG4", signal: "CH1", af: None },
            RawPin { pin: "PG5", signal: "CH2", af: None },
            RawPin { pin: "PG6", signal: "CH3", af: None },
            RawPin { pin: "PG7", signal: "CH4", af: None },
            RawPin { pin: "PG8", signal: "ETR", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM6", address: 0x40001000, block: Some("TIM_BASIC"), pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM7", address: 0x40001400, block: Some("TIM_BASIC"), pins: &[
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "TIM8", address: 0x40013400, block: Some("TIM_ADV"), pins: &[
            RawPin { pin: "PA0", signal: "ETR", af: None },
            RawPin { pin: "PA1", signal: "BKIN", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "CH4N", af: None },
            RawPin { pin: "PA5", signal: "CH1N", af: None },
            RawPin { pin: "PA6", signal: "BKIN", af: None },
            RawPin { pin: "PA7", signal: "CH1N", af: None },
            RawPin { pin: "PA8", signal: "BKIN2", af: None },
            RawPin { pin: "PA9", signal: "CH2N", af: None },
            RawPin { pin: "PB0", signal: "CH2N", af: None },
            RawPin { pin: "PB1", signal: "CH3N", af: None },
            RawPin { pin: "PB10", signal: "CH1", af: None },
            RawPin { pin: "PB12", signal: "CH3", af: None },
            RawPin { pin: "PB13", signal: "CH2", af: None },
            RawPin { pin: "PB14", signal: "CH2N", af: None },
            RawPin { pin: "PB15", signal: "CH3N", af: None },
            RawPin { pin: "PB2", signal: "CH4N", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "CH1", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "CH2", af: None },
            RawPin { pin: "PB5", signal: "CH3", af: None },
            RawPin { pin: "PB6", signal: "CH4", af: None },
            RawPin { pin: "PC10", signal: "CH1N", af: None },
            RawPin { pin: "PC11", signal: "CH2N", af: None },
            RawPin { pin: "PC12", signal: "CH3N", af: None },
            RawPin { pin: "PC4", signal: "BKIN", af: None },
            RawPin { pin: "PC5", signal: "BKIN2", af: None },
            RawPin { pin: "PC6", signal: "CH1", af: None },
            RawPin { pin: "PC7", signal: "CH2", af: None },
            RawPin { pin: "PC8", signal: "CH3", af: None },
            RawPin { pin: "PC9", signal: "CH4", af: None },
            RawPin { pin: "PD0", signal: "CH4N", af: None },
            RawPin { pin: "PD12", signal: "CH1N", af: None },
            RawPin { pin: "PD13", signal: "CH2N", af: None },
            RawPin { pin: "PD14", signal: "CH3N", af: None },
            RawPin { pin: "PD15", signal: "CH4N", af: None },
            RawPin { pin: "PG2", signal: "BKIN", af: None },
            RawPin { pin: "PG3", signal: "BKIN2", af: None },
            RawPin { pin: "PG8", signal: "ETR", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "CC1", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC2", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC3", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "CC4", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "COM", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TRGI", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "UPD", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "UART4", address: 0x40004c00, block: None, pins: &[
            RawPin { pin: "PA0", signal: "TX", af: None },
            RawPin { pin: "PA1", signal: "RX", af: None },
            RawPin { pin: "PA11", signal: "RX", af: None },
            RawPin { pin: "PA12", signal: "TX", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "RTS", af: None },
            RawPin { pin: "PB0", signal: "CTS", af: None },
            RawPin { pin: "PB14", signal: "RTS", af: None },
            RawPin { pin: "PB15", signal: "CTS", af: None },
            RawPin { pin: "PB8", signal: "RX", af: None },
            RawPin { pin: "PB9", signal: "TX", af: None },
            RawPin { pin: "PC10", signal: "TX", af: None },
            RawPin { pin: "PC11", signal: "RX", af: None },
            RawPin { pin: "PD0", signal: "RX", af: None },
            RawPin { pin: "PD1", signal: "TX", af: None },
            RawPin { pin: "PD11", signal: "RX", af: None },
            RawPin { pin: "PD12", signal: "TX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "UART5", address: 0x40005000, block: None, pins: &[
            RawPin { pin: "PB12", signal: "RX", af: None },
            RawPin { pin: "PB13", signal: "TX", af: None },
            RawPin { pin: "PB15", signal: "RX", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "RTS", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "CTS", af: None },
            RawPin { pin: "PB5", signal: "RX", af: None },
            RawPin { pin: "PB6", signal: "TX", af: None },
            RawPin { pin: "PC12", signal: "TX", af: None },
            RawPin { pin: "PC8", signal: "RTS", af: None },
            RawPin { pin: "PC9", signal: "CTS", af: None },
            RawPin { pin: "PD2", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "UART7", address: 0x40007800, block: None, pins: &[
            RawPin { pin: "PA10", signal: "TX", af: None },
            RawPin { pin: "PA8", signal: "RX", af: None },
            RawPin { pin: "PE10", signal: "CTS", af: None },
            RawPin { pin: "PE7", signal: "RX", af: None },
            RawPin { pin: "PE8", signal: "TX", af: None },
            RawPin { pin: "PE9", signal: "RTS", af: None },
            RawPin { pin: "PF6", signal: "RX", af: None },
            RawPin { pin: "PF7", signal: "TX", af: None },
            RawPin { pin: "PF8", signal: "RTS", af: None },
            RawPin { pin: "PF9", signal: "CTS", af: None },
            RawPin { pin: "PG3", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "UID", address: 0x08fff800, block: Some("UID"), pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "USART1", address: 0x40013800, block: None, pins: &[
            RawPin { pin: "PA10", signal: "RX", af: None },
            RawPin { pin: "PA11", signal: "CTS", af: None },
            RawPin { pin: "PA11", signal: "NSS", af: None },
            RawPin { pin: "PA12", signal: "RTS", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "TX", af: None },
            RawPin { pin: "PA5", signal: "CTS", af: None },
            RawPin { pin: "PA5", signal: "NSS", af: None },
            RawPin { pin: "PA6", signal: "TX", af: None },
            RawPin { pin: "PA7", signal: "RX", af: None },
            RawPin { pin: "PA8", signal: "CK", af: None },
            RawPin { pin: "PA9", signal: "TX", af: None },
            RawPin { pin: "PB14", signal: "TX", af: None },
            RawPin { pin: "PB15", signal: "RX", af: None },
            RawPin { pin: "PB6", signal: "TX", af: None },
            RawPin { pin: "PB7", signal: "RX", af: None },
            RawPin { pin: "PE3", signal: "RX", af: None },
            RawPin { pin: "PE4", signal: "TX", af: None },
            RawPin { pin: "PE5", signal: "CK", af: None },
            RawPin { pin: "PE6", signal: "CTS", af: None },
            RawPin { pin: "PE6", signal: "NSS", af: None },
            RawPin { pin: "PH15", signal: "RTS", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "USART2", address: 0x40004400, block: None, pins: &[
            RawPin { pin: "PA0", signal: "CTS", af: None },
            RawPin { pin: "PA0", signal: "NSS", af: None },
            RawPin { pin: "PA1", signal: "RTS", af: None },
            RawPin { pin: "PA11", signal: "TX", af: None },
            RawPin { pin: "PA12", signal: "RX", af: None },
            RawPin { pin: "PA15(JTDI)", signal: "CK", af: None },
            RawPin { pin: "PA2", signal: "TX", af: None },
            RawPin { pin: "PA3", signal: "RX", af: None },
            RawPin { pin: "PA4", signal: "CK", af: None },
            RawPin { pin: "PB0", signal: "TX", af: None },
            RawPin { pin: "PD3", signal: "CTS", af: None },
            RawPin { pin: "PD3", signal: "NSS", af: None },
            RawPin { pin: "PD4", signal: "RTS", af: None },
            RawPin { pin: "PD5", signal: "TX", af: None },
            RawPin { pin: "PD6", signal: "RX", af: None },
            RawPin { pin: "PD7", signal: "CK", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "USART3", address: 0x40004800, block: None, pins: &[
            RawPin { pin: "PB1", signal: "RX", af: None },
            RawPin { pin: "PB10", signal: "TX", af: None },
            RawPin { pin: "PB12", signal: "CK", af: None },
            RawPin { pin: "PB13", signal: "CTS", af: None },
            RawPin { pin: "PB13", signal: "NSS", af: None },
            RawPin { pin: "PB14", signal: "RTS", af: None },
            RawPin { pin: "PB3(JTDO/TRACESWO)", signal: "TX", af: None },
            RawPin { pin: "PB4(NJTRST)", signal: "RX", af: None },
            RawPin { pin: "PB5", signal: "CK", af: None },
            RawPin { pin: "PB6", signal: "CTS", af: None },
            RawPin { pin: "PB6", signal: "NSS", af: None },
            RawPin { pin: "PB7", signal: "RTS", af: None },
            RawPin { pin: "PC10", signal: "TX", af: None },
            RawPin { pin: "PC11", signal: "RX", af: None },
            RawPin { pin: "PC12", signal: "CK", af: None },
            RawPin { pin: "PC4", signal: "RX", af: None },
            RawPin { pin: "PD10", signal: "CK", af: None },
            RawPin { pin: "PD11", signal: "CTS", af: None },
            RawPin { pin: "PD11", signal: "NSS", af: None },
            RawPin { pin: "PD12", signal: "RTS", af: None },
            RawPin { pin: "PD8", signal: "TX", af: None },
            RawPin { pin: "PD9", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "USART6", address: 0x40006400, block: None, pins: &[
            RawPin { pin: "PC6", signal: "TX", af: None },
            RawPin { pin: "PC7", signal: "RX", af: None },
            RawPin { pin: "PC8", signal: "CK", af: None },
            RawPin { pin: "PG10", signal: "CK", af: None },
            RawPin { pin: "PG12", signal: "RTS", af: None },
            RawPin { pin: "PG13", signal: "CTS", af: None },
            RawPin { pin: "PG13", signal: "NSS", af: None },
            RawPin { pin: "PG14", signal: "TX", af: None },
            RawPin { pin: "PG15", signal: "CTS", af: None },
            RawPin { pin: "PG15", signal: "NSS", af: None },
            RawPin { pin: "PG7", signal: "CK", af: None },
            RawPin { pin: "PG8", signal: "RTS", af: None },
            RawPin { pin: "PG9", signal: "RX", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "RX", pools: &["LPDMA1", "LPDMA2"] },
            RawDmaLeg { signal: "TX", pools: &["LPDMA1", "LPDMA2"] },
        ] },
        RawPeripheral { name: "USBRAM", address: 0x40016400, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "WWDG", address: 0x40002c00, block: None, pins: &[
        ], triggers: &[
        ], dma: &[
        ] },
        RawPeripheral { name: "XSPI1", address: 0x47001400, block: None, pins: &[
            RawPin { pin: "PA0", signal: "IO3", af: None },
            RawPin { pin: "PA1", signal: "DQS", af: None },
            RawPin { pin: "PA1", signal: "IO3", af: None },
            RawPin { pin: "PA10", signal: "CLK", af: None },
            RawPin { pin: "PA11", signal: "NCS2", af: None },
            RawPin { pin: "PA2", signal: "NCLK", af: None },
            RawPin { pin: "PA3", signal: "CLK", af: None },
            RawPin { pin: "PA5", signal: "IO1", af: None },
            RawPin { pin: "PA5", signal: "NCS1", af: None },
            RawPin { pin: "PA6", signal: "IO3", af: None },
            RawPin { pin: "PA7", signal: "IO2", af: None },
            RawPin { pin: "PA8", signal: "IO6", af: None },
            RawPin { pin: "PA9", signal: "IO7", af: None },
            RawPin { pin: "PB0", signal: "IO1", af: None },
            RawPin { pin: "PB1", signal: "IO0", af: None },
            RawPin { pin: "PB10", signal: "NCS1", af: None },
            RawPin { pin: "PB12", signal: "NCLK", af: None },
            RawPin { pin: "PB13", signal: "DQS", af: None },
            RawPin { pin: "PB15", signal: "CLK", af: None },
            RawPin { pin: "PB15", signal: "IO0", af: None },
            RawPin { pin: "PB2", signal: "CLK", af: None },
            RawPin { pin: "PB2", signal: "DQS", af: None },
            RawPin { pin: "PB8", signal: "NCS1", af: None },
            RawPin { pin: "PC0", signal: "IO7", af: None },
            RawPin { pin: "PC1", signal: "IO4", af: None },
            RawPin { pin: "PC1", signal: "IO6", af: None },
            RawPin { pin: "PC10", signal: "IO1", af: None },
            RawPin { pin: "PC11", signal: "NCS1", af: None },
            RawPin { pin: "PC2", signal: "IO2", af: None },
            RawPin { pin: "PC2", signal: "IO5", af: None },
            RawPin { pin: "PC3", signal: "IO0", af: None },
            RawPin { pin: "PC3", signal: "IO4", af: None },
            RawPin { pin: "PC3", signal: "IO6", af: None },
            RawPin { pin: "PC5", signal: "DQS", af: None },
            RawPin { pin: "PC6", signal: "IO3", af: None },
            RawPin { pin: "PC6", signal: "IO5", af: None },
            RawPin { pin: "PC7", signal: "IO4", af: None },
            RawPin { pin: "PC7", signal: "IO6", af: None },
            RawPin { pin: "PC9", signal: "IO0", af: None },
            RawPin { pin: "PC9", signal: "IO5", af: None },
            RawPin { pin: "PD0", signal: "NCS2", af: None },
            RawPin { pin: "PD11", signal: "IO0", af: None },
            RawPin { pin: "PD12", signal: "IO1", af: None },
            RawPin { pin: "PD13", signal: "IO2", af: None },
            RawPin { pin: "PD13", signal: "IO3", af: None },
            RawPin { pin: "PD2", signal: "NCS2", af: None },
            RawPin { pin: "PD4", signal: "IO4", af: None },
            RawPin { pin: "PD5", signal: "IO5", af: None },
            RawPin { pin: "PD6", signal: "IO6", af: None },
            RawPin { pin: "PD7", signal: "IO7", af: None },
            RawPin { pin: "PE0", signal: "NCS2", af: None },
            RawPin { pin: "PE10", signal: "IO7", af: None },
            RawPin { pin: "PE11", signal: "NCS1", af: None },
            RawPin { pin: "PE2", signal: "IO2", af: None },
            RawPin { pin: "PE7", signal: "IO4", af: None },
            RawPin { pin: "PE8", signal: "IO5", af: None },
            RawPin { pin: "PE9", signal: "IO6", af: None },
            RawPin { pin: "PF10", signal: "CLK", af: None },
            RawPin { pin: "PF11", signal: "NCLK", af: None },
            RawPin { pin: "PF6", signal: "IO3", af: None },
            RawPin { pin: "PF7", signal: "IO2", af: None },
            RawPin { pin: "PF8", signal: "IO1", af: None },
            RawPin { pin: "PF9", signal: "IO0", af: None },
            RawPin { pin: "PG14", signal: "IO7", af: None },
            RawPin { pin: "PG6", signal: "NCS1", af: None },
            RawPin { pin: "PG9", signal: "IO6", af: None },
        ], triggers: &[
        ], dma: &[
            RawDmaLeg { signal: "GLOBAL", pools: &["LPDMA1", "LPDMA2"] },
        ] },
    ],
    dma_pools: &[
        DmaPoolDef { name: "LPDMA1", channels: 8 },
        DmaPoolDef { name: "LPDMA2", channels: 8 },
    ],
};
