// GENERATED by `cargo run --bin extract` — do not edit by hand.
// Source: stm32-metapac chip STM32H523HE (STM32H5 family).

use crate::mcu_raw::{RawMcuData, RawPeripheral, RawPin};

pub static RAW: RawMcuData = RawMcuData {
    name: "STM32H523HE",
    family: "STM32H5",
    peripherals: &[
        RawPeripheral { name: "ADC1", address: 0x42028000, pins: &[
            RawPin { pin: "PA0", signal: "INN1", af: None },
            RawPin { pin: "PA0", signal: "INP0", af: None },
            RawPin { pin: "PA1", signal: "INP1", af: None },
            RawPin { pin: "PA2", signal: "INP14", af: None },
            RawPin { pin: "PA3", signal: "INP15", af: None },
            RawPin { pin: "PA4", signal: "INP18", af: None },
            RawPin { pin: "PA5", signal: "INN18", af: None },
            RawPin { pin: "PA5", signal: "INP19", af: None },
            RawPin { pin: "PA6", signal: "INP3", af: None },
            RawPin { pin: "PA7", signal: "INN3", af: None },
            RawPin { pin: "PA7", signal: "INP7", af: None },
            RawPin { pin: "PB0", signal: "INN5", af: None },
            RawPin { pin: "PB0", signal: "INP9", af: None },
            RawPin { pin: "PB1", signal: "INP5", af: None },
        ] },
        RawPeripheral { name: "ADC12_COMMON", address: 0x42028300, pins: &[
        ] },
        RawPeripheral { name: "ADC2", address: 0x42028100, pins: &[
            RawPin { pin: "PA0", signal: "INN1", af: None },
            RawPin { pin: "PA0", signal: "INP0", af: None },
            RawPin { pin: "PA1", signal: "INP1", af: None },
            RawPin { pin: "PA2", signal: "INP14", af: None },
            RawPin { pin: "PA3", signal: "INP15", af: None },
            RawPin { pin: "PA4", signal: "INP18", af: None },
            RawPin { pin: "PA5", signal: "INN18", af: None },
            RawPin { pin: "PA5", signal: "INP19", af: None },
            RawPin { pin: "PA6", signal: "INP3", af: None },
            RawPin { pin: "PA7", signal: "INN3", af: None },
            RawPin { pin: "PA7", signal: "INP7", af: None },
            RawPin { pin: "PB0", signal: "INN5", af: None },
            RawPin { pin: "PB0", signal: "INP9", af: None },
            RawPin { pin: "PB1", signal: "INP5", af: None },
        ] },
        RawPeripheral { name: "CEC", address: 0x40007000, pins: &[
            RawPin { pin: "PA15", signal: "CEC", af: Some(4) },
        ] },
        RawPeripheral { name: "CRC", address: 0x40023000, pins: &[
        ] },
        RawPeripheral { name: "CRS", address: 0x40006000, pins: &[
            RawPin { pin: "PB3", signal: "SYNC", af: Some(10) },
        ] },
        RawPeripheral { name: "DAC1", address: 0x42028400, pins: &[
            RawPin { pin: "PA4", signal: "OUT1", af: None },
            RawPin { pin: "PA5", signal: "OUT2", af: None },
        ] },
        RawPeripheral { name: "DBGMCU", address: 0x44024000, pins: &[
        ] },
        RawPeripheral { name: "DCACHE1", address: 0x40031400, pins: &[
        ] },
        RawPeripheral { name: "DTS", address: 0x40008c00, pins: &[
        ] },
        RawPeripheral { name: "EXTI", address: 0x44022000, pins: &[
        ] },
        RawPeripheral { name: "FDCAN1", address: 0x4000a400, pins: &[
            RawPin { pin: "PA11", signal: "RX", af: Some(9) },
            RawPin { pin: "PA12", signal: "TX", af: Some(9) },
            RawPin { pin: "PB7", signal: "TX", af: Some(9) },
            RawPin { pin: "PB8", signal: "RX", af: Some(9) },
        ] },
        RawPeripheral { name: "FDCAN2", address: 0x4000a800, pins: &[
            RawPin { pin: "PA0", signal: "RX", af: Some(9) },
            RawPin { pin: "PB3", signal: "TX", af: Some(9) },
        ] },
        RawPeripheral { name: "FDCANRAM1", address: 0x4000ac00, pins: &[
        ] },
        RawPeripheral { name: "FDCANRAM2", address: 0x4000af50, pins: &[
        ] },
        RawPeripheral { name: "FLASH", address: 0x40022000, pins: &[
        ] },
        RawPeripheral { name: "GPDMA1", address: 0x40020000, pins: &[
        ] },
        RawPeripheral { name: "GPDMA2", address: 0x40021000, pins: &[
        ] },
        RawPeripheral { name: "GPIOA", address: 0x42020000, pins: &[
        ] },
        RawPeripheral { name: "GPIOB", address: 0x42020400, pins: &[
        ] },
        RawPeripheral { name: "GPIOC", address: 0x42020800, pins: &[
        ] },
        RawPeripheral { name: "GPIOD", address: 0x42020c00, pins: &[
        ] },
        RawPeripheral { name: "GPIOE", address: 0x42021000, pins: &[
        ] },
        RawPeripheral { name: "GPIOF", address: 0x42021400, pins: &[
        ] },
        RawPeripheral { name: "GPIOG", address: 0x42021800, pins: &[
        ] },
        RawPeripheral { name: "GPIOH", address: 0x42021c00, pins: &[
        ] },
        RawPeripheral { name: "GTZC", address: 0x40032400, pins: &[
        ] },
        RawPeripheral { name: "HASH", address: 0x420c0400, pins: &[
        ] },
        RawPeripheral { name: "I2C1", address: 0x40005400, pins: &[
            RawPin { pin: "PB7", signal: "SDA", af: Some(4) },
            RawPin { pin: "PB8", signal: "SCL", af: Some(4) },
        ] },
        RawPeripheral { name: "I2C2", address: 0x40005800, pins: &[
            RawPin { pin: "PB3", signal: "SDA", af: Some(4) },
        ] },
        RawPeripheral { name: "I3C1", address: 0x40005c00, pins: &[
            RawPin { pin: "PB7", signal: "SDA", af: Some(3) },
            RawPin { pin: "PB8", signal: "SCL", af: Some(3) },
        ] },
        RawPeripheral { name: "I3C2", address: 0x44003000, pins: &[
            RawPin { pin: "PA8", signal: "SCL", af: Some(9) },
            RawPin { pin: "PB3", signal: "SCL", af: Some(3) },
            RawPin { pin: "PB4", signal: "SDA", af: Some(10) },
        ] },
        RawPeripheral { name: "ICACHE", address: 0x40030400, pins: &[
        ] },
        RawPeripheral { name: "IWDG", address: 0x40003000, pins: &[
        ] },
        RawPeripheral { name: "LPTIM1", address: 0x44004400, pins: &[
            RawPin { pin: "PA1", signal: "IN1", af: Some(5) },
            RawPin { pin: "PA2", signal: "IN2", af: Some(5) },
            RawPin { pin: "PB4", signal: "CH2", af: Some(4) },
        ] },
        RawPeripheral { name: "LPTIM2", address: 0x40009400, pins: &[
            RawPin { pin: "PA4", signal: "CH1", af: Some(3) },
        ] },
        RawPeripheral { name: "LPUART1", address: 0x44002400, pins: &[
            RawPin { pin: "PA11", signal: "CTS", af: Some(3) },
            RawPin { pin: "PA12", signal: "DE", af: Some(3) },
            RawPin { pin: "PA12", signal: "RTS", af: Some(3) },
            RawPin { pin: "PA2", signal: "TX", af: Some(3) },
            RawPin { pin: "PB3", signal: "TX", af: Some(8) },
            RawPin { pin: "PB7", signal: "RX", af: Some(8) },
        ] },
        RawPeripheral { name: "OCTOSPI1", address: 0x47001400, pins: &[
            RawPin { pin: "PA1", signal: "DQS", af: Some(6) },
            RawPin { pin: "PA1", signal: "IO3", af: Some(9) },
            RawPin { pin: "PA15", signal: "NCS", af: Some(9) },
            RawPin { pin: "PA3", signal: "CLK", af: Some(3) },
            RawPin { pin: "PA6", signal: "IO3", af: Some(6) },
            RawPin { pin: "PA7", signal: "IO2", af: Some(10) },
            RawPin { pin: "PB0", signal: "IO1", af: Some(6) },
            RawPin { pin: "PB1", signal: "IO0", af: Some(6) },
            RawPin { pin: "PB15", signal: "CLK", af: Some(10) },
            RawPin { pin: "PB4", signal: "CLK", af: Some(3) },
        ] },
        RawPeripheral { name: "PKA", address: 0x420c2000, pins: &[
        ] },
        RawPeripheral { name: "PWR", address: 0x44020800, pins: &[
            RawPin { pin: "PA0", signal: "WKUP1", af: None },
            RawPin { pin: "PA2", signal: "WKUP2", af: None },
            RawPin { pin: "PB15", signal: "PVD_IN", af: None },
            RawPin { pin: "PB7", signal: "WKUP5", af: None },
            RawPin { pin: "PC13", signal: "WKUP4", af: None },
        ] },
        RawPeripheral { name: "RAMCFG", address: 0x40026000, pins: &[
        ] },
        RawPeripheral { name: "RCC", address: 0x44020c00, pins: &[
            RawPin { pin: "PA8", signal: "MCO_1", af: Some(0) },
            RawPin { pin: "PC14", signal: "OSC32_IN", af: None },
            RawPin { pin: "PC15", signal: "OSC32_OUT", af: None },
            RawPin { pin: "PH0", signal: "OSC_IN", af: None },
            RawPin { pin: "PH1", signal: "OSC_OUT", af: None },
        ] },
        RawPeripheral { name: "RNG", address: 0x420c0800, pins: &[
        ] },
        RawPeripheral { name: "RTC", address: 0x44007800, pins: &[
            RawPin { pin: "PB15", signal: "REFIN", af: Some(0) },
            RawPin { pin: "PC13", signal: "OUT1", af: None },
            RawPin { pin: "PC13", signal: "TS", af: None },
        ] },
        RawPeripheral { name: "SPI1", address: 0x40013000, pins: &[
            RawPin { pin: "PA15", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA15", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA4", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA4", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA5", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PA5", signal: "SCK", af: Some(5) },
            RawPin { pin: "PA6", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PA6", signal: "MISO", af: Some(5) },
            RawPin { pin: "PA7", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PA7", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PA8", signal: "RDY", af: Some(5) },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: Some(6) },
            RawPin { pin: "PB15", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PB3", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PB3", signal: "SCK", af: Some(5) },
            RawPin { pin: "PB4", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PB4", signal: "MISO", af: Some(5) },
        ] },
        RawPeripheral { name: "SPI2", address: 0x40003800, pins: &[
            RawPin { pin: "PA11", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA11", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA12", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PA12", signal: "SCK", af: Some(5) },
            RawPin { pin: "PA3", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA3", signal: "NSS", af: Some(5) },
            RawPin { pin: "PB1", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PB1", signal: "NSS", af: Some(5) },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PB15", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PB4", signal: "I2S_WS", af: Some(7) },
            RawPin { pin: "PB4", signal: "NSS", af: Some(7) },
        ] },
        RawPeripheral { name: "SPI3", address: 0x40003c00, pins: &[
            RawPin { pin: "PA0", signal: "RDY", af: Some(6) },
            RawPin { pin: "PA15", signal: "NSS", af: Some(6) },
            RawPin { pin: "PA3", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PA4", signal: "MOSI", af: Some(4) },
            RawPin { pin: "PA4", signal: "NSS", af: Some(6) },
            RawPin { pin: "PB0", signal: "MISO", af: Some(5) },
            RawPin { pin: "PB1", signal: "SCK", af: Some(4) },
            RawPin { pin: "PB3", signal: "SCK", af: Some(6) },
            RawPin { pin: "PB4", signal: "MISO", af: Some(6) },
            RawPin { pin: "PB8", signal: "NSS", af: Some(6) },
        ] },
        RawPeripheral { name: "SYSCFG", address: 0x44000400, pins: &[
        ] },
        RawPeripheral { name: "TAMP", address: 0x44007c00, pins: &[
            RawPin { pin: "PA0", signal: "IN2", af: None },
            RawPin { pin: "PA0", signal: "OUT1", af: None },
            RawPin { pin: "PA1", signal: "IN5", af: None },
            RawPin { pin: "PA1", signal: "OUT4", af: None },
            RawPin { pin: "PA2", signal: "IN4", af: None },
            RawPin { pin: "PA2", signal: "OUT3", af: None },
            RawPin { pin: "PC13", signal: "IN1", af: None },
            RawPin { pin: "PC13", signal: "OUT2", af: None },
            RawPin { pin: "PC13", signal: "OUT3", af: None },
        ] },
        RawPeripheral { name: "TIM1", address: 0x40012c00, pins: &[
            RawPin { pin: "PA11", signal: "CH4", af: Some(1) },
            RawPin { pin: "PA12", signal: "ETR", af: Some(1) },
            RawPin { pin: "PA6", signal: "BKIN", af: Some(1) },
            RawPin { pin: "PA7", signal: "CH1N", af: Some(1) },
            RawPin { pin: "PA8", signal: "CH1", af: Some(1) },
            RawPin { pin: "PB0", signal: "CH2N", af: Some(1) },
            RawPin { pin: "PB1", signal: "CH3N", af: Some(1) },
            RawPin { pin: "PB15", signal: "CH3N", af: Some(1) },
        ] },
        RawPeripheral { name: "TIM12", address: 0x40001800, pins: &[
            RawPin { pin: "PB15", signal: "CH2", af: Some(2) },
        ] },
        RawPeripheral { name: "TIM15", address: 0x40014000, pins: &[
            RawPin { pin: "PA0", signal: "BKIN", af: Some(4) },
            RawPin { pin: "PA1", signal: "CH1N", af: Some(4) },
            RawPin { pin: "PA2", signal: "CH1", af: Some(4) },
            RawPin { pin: "PA3", signal: "CH2", af: Some(4) },
        ] },
        RawPeripheral { name: "TIM2", address: 0x40000000, pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA0", signal: "ETR", af: Some(14) },
            RawPin { pin: "PA1", signal: "CH2", af: Some(1) },
            RawPin { pin: "PA15", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA15", signal: "ETR", af: Some(14) },
            RawPin { pin: "PA2", signal: "CH3", af: Some(1) },
            RawPin { pin: "PA3", signal: "CH4", af: Some(1) },
            RawPin { pin: "PA5", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA5", signal: "ETR", af: Some(14) },
            RawPin { pin: "PB3", signal: "CH2", af: Some(1) },
        ] },
        RawPeripheral { name: "TIM3", address: 0x40000400, pins: &[
            RawPin { pin: "PA6", signal: "CH1", af: Some(2) },
            RawPin { pin: "PA7", signal: "CH2", af: Some(2) },
            RawPin { pin: "PB0", signal: "CH3", af: Some(2) },
            RawPin { pin: "PB1", signal: "CH4", af: Some(2) },
            RawPin { pin: "PB4", signal: "CH1", af: Some(2) },
        ] },
        RawPeripheral { name: "TIM4", address: 0x40000800, pins: &[
            RawPin { pin: "PB7", signal: "CH2", af: Some(2) },
            RawPin { pin: "PB8", signal: "CH3", af: Some(2) },
        ] },
        RawPeripheral { name: "TIM5", address: 0x40000c00, pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: Some(2) },
            RawPin { pin: "PA1", signal: "CH2", af: Some(2) },
            RawPin { pin: "PA2", signal: "CH3", af: Some(2) },
            RawPin { pin: "PA3", signal: "CH4", af: Some(2) },
            RawPin { pin: "PA4", signal: "ETR", af: Some(2) },
        ] },
        RawPeripheral { name: "TIM6", address: 0x40001000, pins: &[
        ] },
        RawPeripheral { name: "TIM7", address: 0x40001400, pins: &[
        ] },
        RawPeripheral { name: "TIM8", address: 0x40013400, pins: &[
            RawPin { pin: "PA0", signal: "ETR", af: Some(3) },
            RawPin { pin: "PA5", signal: "CH1N", af: Some(3) },
            RawPin { pin: "PA6", signal: "BKIN", af: Some(3) },
            RawPin { pin: "PA7", signal: "CH1N", af: Some(3) },
            RawPin { pin: "PA8", signal: "BKIN2", af: Some(3) },
            RawPin { pin: "PB0", signal: "CH2N", af: Some(3) },
            RawPin { pin: "PB1", signal: "CH3N", af: Some(3) },
            RawPin { pin: "PB15", signal: "CH3N", af: Some(3) },
        ] },
        RawPeripheral { name: "UART4", address: 0x40004c00, pins: &[
            RawPin { pin: "PA0", signal: "TX", af: Some(8) },
            RawPin { pin: "PA1", signal: "RX", af: Some(8) },
            RawPin { pin: "PA11", signal: "RX", af: Some(6) },
            RawPin { pin: "PA12", signal: "TX", af: Some(6) },
            RawPin { pin: "PA15", signal: "DE", af: Some(8) },
            RawPin { pin: "PA15", signal: "RTS", af: Some(8) },
            RawPin { pin: "PB0", signal: "CTS", af: Some(8) },
            RawPin { pin: "PB15", signal: "CTS", af: Some(8) },
            RawPin { pin: "PB8", signal: "RX", af: Some(8) },
        ] },
        RawPeripheral { name: "UART5", address: 0x40005000, pins: &[
            RawPin { pin: "PB15", signal: "RX", af: Some(14) },
            RawPin { pin: "PB3", signal: "TX", af: Some(14) },
        ] },
        RawPeripheral { name: "UID", address: 0x08fff800, pins: &[
        ] },
        RawPeripheral { name: "USART1", address: 0x40013800, pins: &[
            RawPin { pin: "PA11", signal: "CTS", af: Some(7) },
            RawPin { pin: "PA11", signal: "NSS", af: Some(7) },
            RawPin { pin: "PA12", signal: "DE", af: Some(7) },
            RawPin { pin: "PA12", signal: "RTS", af: Some(7) },
            RawPin { pin: "PA15", signal: "TX", af: Some(7) },
            RawPin { pin: "PA8", signal: "CK", af: Some(7) },
            RawPin { pin: "PB15", signal: "RX", af: Some(4) },
            RawPin { pin: "PB7", signal: "RX", af: Some(7) },
        ] },
        RawPeripheral { name: "USART2", address: 0x40004400, pins: &[
            RawPin { pin: "PA0", signal: "CTS", af: Some(7) },
            RawPin { pin: "PA0", signal: "NSS", af: Some(7) },
            RawPin { pin: "PA1", signal: "DE", af: Some(7) },
            RawPin { pin: "PA1", signal: "RTS", af: Some(7) },
            RawPin { pin: "PA2", signal: "TX", af: Some(7) },
            RawPin { pin: "PA3", signal: "RX", af: Some(7) },
            RawPin { pin: "PA4", signal: "CK", af: Some(7) },
            RawPin { pin: "PB0", signal: "TX", af: Some(7) },
        ] },
        RawPeripheral { name: "USB", address: 0x40016000, pins: &[
            RawPin { pin: "PA11", signal: "DM", af: Some(10) },
            RawPin { pin: "PA12", signal: "DP", af: Some(10) },
            RawPin { pin: "PA8", signal: "SOF", af: Some(10) },
        ] },
        RawPeripheral { name: "USBRAM", address: 0x40016400, pins: &[
        ] },
        RawPeripheral { name: "VREFBUF", address: 0x44007400, pins: &[
        ] },
        RawPeripheral { name: "WWDG", address: 0x40002c00, pins: &[
        ] },
    ],
};
