// GENERATED by `cargo run --bin extract` — do not edit by hand.
// Source: stm32-metapac chip STM32H523RE (STM32H5 family).

use crate::mcu_raw::{RawMcuData, RawPeripheral, RawPin, RawTrigger};

pub static RAW: RawMcuData = RawMcuData {
    name: "STM32H523RE",
    family: "STM32H5",
    peripherals: &[
        RawPeripheral { name: "ADC1", address: 0x42028000, block: Some("ADC"), pins: &[
            RawPin { pin: "PA0", signal: "INN1", af: None },
            RawPin { pin: "PA0", signal: "INP0", af: None },
            RawPin { pin: "PA1", signal: "INP1", af: None },
            RawPin { pin: "PA2", signal: "INP14", af: None },
            RawPin { pin: "PA3", signal: "INP15", af: None },
            RawPin { pin: "PA4", signal: "INP18", af: None },
            RawPin { pin: "PA5", signal: "INN18", af: None },
            RawPin { pin: "PA5", signal: "INP19", af: None },
            RawPin { pin: "PA6", signal: "INP3", af: None },
            RawPin { pin: "PA7", signal: "INN3", af: None },
            RawPin { pin: "PA7", signal: "INP7", af: None },
            RawPin { pin: "PB0", signal: "INN5", af: None },
            RawPin { pin: "PB0", signal: "INP9", af: None },
            RawPin { pin: "PB1", signal: "INP5", af: None },
            RawPin { pin: "PC0", signal: "INP10", af: None },
            RawPin { pin: "PC1", signal: "INN10", af: None },
            RawPin { pin: "PC1", signal: "INP11", af: None },
            RawPin { pin: "PC2", signal: "INN11", af: None },
            RawPin { pin: "PC2", signal: "INP12", af: None },
            RawPin { pin: "PC3", signal: "INN12", af: None },
            RawPin { pin: "PC3", signal: "INP13", af: None },
            RawPin { pin: "PC4", signal: "INP4", af: None },
            RawPin { pin: "PC5", signal: "INN4", af: None },
            RawPin { pin: "PC5", signal: "INP8", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "ADC12_COMMON", address: 0x42028300, block: Some("ADC_COMMON"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "ADC2", address: 0x42028100, block: Some("ADC"), pins: &[
            RawPin { pin: "PA0", signal: "INN1", af: None },
            RawPin { pin: "PA0", signal: "INP0", af: None },
            RawPin { pin: "PA1", signal: "INP1", af: None },
            RawPin { pin: "PA2", signal: "INP14", af: None },
            RawPin { pin: "PA3", signal: "INP15", af: None },
            RawPin { pin: "PA4", signal: "INP18", af: None },
            RawPin { pin: "PA5", signal: "INN18", af: None },
            RawPin { pin: "PA5", signal: "INP19", af: None },
            RawPin { pin: "PA6", signal: "INP3", af: None },
            RawPin { pin: "PA7", signal: "INN3", af: None },
            RawPin { pin: "PA7", signal: "INP7", af: None },
            RawPin { pin: "PB0", signal: "INN5", af: None },
            RawPin { pin: "PB0", signal: "INP9", af: None },
            RawPin { pin: "PB1", signal: "INP5", af: None },
            RawPin { pin: "PC0", signal: "INP10", af: None },
            RawPin { pin: "PC1", signal: "INN10", af: None },
            RawPin { pin: "PC1", signal: "INP11", af: None },
            RawPin { pin: "PC2", signal: "INN11", af: None },
            RawPin { pin: "PC2", signal: "INP12", af: None },
            RawPin { pin: "PC3", signal: "INN12", af: None },
            RawPin { pin: "PC3", signal: "INP13", af: None },
            RawPin { pin: "PC4", signal: "INP4", af: None },
            RawPin { pin: "PC5", signal: "INN4", af: None },
            RawPin { pin: "PC5", signal: "INP8", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "CEC", address: 0x40007000, block: Some("CEC"), pins: &[
            RawPin { pin: "PA15", signal: "CEC", af: Some(4) },
            RawPin { pin: "PB6", signal: "CEC", af: Some(5) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "CRC", address: 0x40023000, block: Some("CRC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "CRS", address: 0x40006000, block: Some("CRS"), pins: &[
            RawPin { pin: "PB3", signal: "SYNC", af: Some(10) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "DAC1", address: 0x42028400, block: Some("DAC"), pins: &[
            RawPin { pin: "PA4", signal: "OUT1", af: None },
            RawPin { pin: "PA5", signal: "OUT2", af: None },
        ], triggers: &[
            RawTrigger { signal: "DAC_CHX_TRG1", source: "TIM1_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG2", source: "TIM2_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG5", source: "TIM6_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG6", source: "TIM7_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO" },
            RawTrigger { signal: "DAC_CHX_TRG13", source: "EXTI9_TRG" },
        ] },
        RawPeripheral { name: "DBGMCU", address: 0x44024000, block: Some("DBGMCU"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "DCACHE1", address: 0x40031400, block: Some("DCACHE"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "DCMI", address: 0x4202c000, block: Some("DCMI"), pins: &[
            RawPin { pin: "PA10", signal: "D1", af: Some(13) },
            RawPin { pin: "PA15", signal: "D11", af: Some(13) },
            RawPin { pin: "PA4", signal: "HSYNC", af: Some(13) },
            RawPin { pin: "PA6", signal: "PIXCLK", af: Some(13) },
            RawPin { pin: "PA8", signal: "D3", af: Some(13) },
            RawPin { pin: "PA9", signal: "D0", af: Some(13) },
            RawPin { pin: "PB15", signal: "D2", af: Some(13) },
            RawPin { pin: "PB4", signal: "D7", af: Some(13) },
            RawPin { pin: "PB5", signal: "D10", af: Some(13) },
            RawPin { pin: "PB6", signal: "D5", af: Some(13) },
            RawPin { pin: "PB7", signal: "VSYNC", af: Some(13) },
            RawPin { pin: "PB8", signal: "D6", af: Some(13) },
            RawPin { pin: "PC10", signal: "D8", af: Some(13) },
            RawPin { pin: "PC11", signal: "D4", af: Some(13) },
            RawPin { pin: "PC12", signal: "D9", af: Some(13) },
            RawPin { pin: "PC6", signal: "D0", af: Some(13) },
            RawPin { pin: "PC7", signal: "D1", af: Some(13) },
            RawPin { pin: "PC8", signal: "D2", af: Some(13) },
            RawPin { pin: "PC9", signal: "D3", af: Some(13) },
            RawPin { pin: "PD2", signal: "D11", af: Some(13) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "DLYB_OCTOSPI1", address: 0x4600f000, block: Some("DLYB"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "DLYB_SDMMC1", address: 0x46008400, block: Some("DLYB"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "DTS", address: 0x40008c00, block: Some("DTS"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "EXTI", address: 0x44022000, block: Some("EXTI"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "FDCAN1", address: 0x4000a400, block: Some("FDCAN"), pins: &[
            RawPin { pin: "PA11", signal: "RX", af: Some(9) },
            RawPin { pin: "PA12", signal: "TX", af: Some(9) },
            RawPin { pin: "PB7", signal: "TX", af: Some(9) },
            RawPin { pin: "PB8", signal: "RX", af: Some(9) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "FDCAN2", address: 0x4000a800, block: Some("FDCAN"), pins: &[
            RawPin { pin: "PA0", signal: "RX", af: Some(9) },
            RawPin { pin: "PA10", signal: "TX", af: Some(9) },
            RawPin { pin: "PB12", signal: "RX", af: Some(9) },
            RawPin { pin: "PB13", signal: "TX", af: Some(9) },
            RawPin { pin: "PB3", signal: "TX", af: Some(9) },
            RawPin { pin: "PB5", signal: "RX", af: Some(9) },
            RawPin { pin: "PB6", signal: "TX", af: Some(9) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "FDCANRAM1", address: 0x4000ac00, block: Some("FDCANRAM"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "FDCANRAM2", address: 0x4000af50, block: Some("FDCANRAM"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "FLASH", address: 0x40022000, block: Some("FLASH"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPDMA1", address: 0x40020000, block: Some("GPDMA"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPDMA2", address: 0x40021000, block: Some("GPDMA"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOA", address: 0x42020000, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOB", address: 0x42020400, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOC", address: 0x42020800, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOD", address: 0x42020c00, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOE", address: 0x42021000, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOF", address: 0x42021400, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOG", address: 0x42021800, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GPIOH", address: 0x42021c00, block: Some("GPIO"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC", address: 0x40032400, block: Some("GTZC1_TZSC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC_MPCBB1", address: 0x40032c00, block: Some("MPCBB"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC_MPCBB2", address: 0x40033000, block: Some("MPCBB"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC_MPCBB3", address: 0x40033400, block: Some("MPCBB"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC_TZIC", address: 0x40032800, block: Some("TZIC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "GTZC_TZSC", address: 0x40032400, block: Some("GTZC1_TZSC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "HASH", address: 0x420c0400, block: Some("HASH"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "I2C1", address: 0x40005400, block: Some("I2C"), pins: &[
            RawPin { pin: "PB5", signal: "SMBA", af: Some(4) },
            RawPin { pin: "PB6", signal: "SCL", af: Some(4) },
            RawPin { pin: "PB7", signal: "SDA", af: Some(4) },
            RawPin { pin: "PB8", signal: "SCL", af: Some(4) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "I2C2", address: 0x40005800, block: Some("I2C"), pins: &[
            RawPin { pin: "PB10", signal: "SCL", af: Some(4) },
            RawPin { pin: "PB12", signal: "SDA", af: Some(4) },
            RawPin { pin: "PB13", signal: "SMBA", af: Some(4) },
            RawPin { pin: "PB3", signal: "SDA", af: Some(4) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "I2C3", address: 0x44002800, block: Some("I2C"), pins: &[
            RawPin { pin: "PA8", signal: "SCL", af: Some(4) },
            RawPin { pin: "PA9", signal: "SMBA", af: Some(4) },
            RawPin { pin: "PB4", signal: "SDA", af: Some(9) },
            RawPin { pin: "PC9", signal: "SDA", af: Some(4) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "I3C1", address: 0x40005c00, block: Some("I3C"), pins: &[
            RawPin { pin: "PB6", signal: "SCL", af: Some(3) },
            RawPin { pin: "PB7", signal: "SDA", af: Some(3) },
            RawPin { pin: "PB8", signal: "SCL", af: Some(3) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "I3C2", address: 0x44003000, block: Some("I3C"), pins: &[
            RawPin { pin: "PA8", signal: "SCL", af: Some(9) },
            RawPin { pin: "PB3", signal: "SCL", af: Some(3) },
            RawPin { pin: "PB4", signal: "SDA", af: Some(10) },
            RawPin { pin: "PB5", signal: "SCL", af: Some(10) },
            RawPin { pin: "PC10", signal: "SCL", af: Some(3) },
            RawPin { pin: "PC11", signal: "SDA", af: Some(3) },
            RawPin { pin: "PC6", signal: "SCL", af: Some(10) },
            RawPin { pin: "PC7", signal: "SDA", af: Some(10) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "ICACHE", address: 0x40030400, block: None, pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "IWDG", address: 0x40003000, block: Some("IWDG"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "LPTIM1", address: 0x44004400, block: Some("LPTIM"), pins: &[
            RawPin { pin: "PA1", signal: "IN1", af: Some(5) },
            RawPin { pin: "PA2", signal: "IN2", af: Some(5) },
            RawPin { pin: "PB2", signal: "CH1", af: Some(5) },
            RawPin { pin: "PB4", signal: "CH2", af: Some(4) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "LPTIM2", address: 0x40009400, block: Some("LPTIM"), pins: &[
            RawPin { pin: "PA10", signal: "IN2", af: Some(4) },
            RawPin { pin: "PA4", signal: "CH1", af: Some(3) },
            RawPin { pin: "PB10", signal: "IN1", af: Some(3) },
            RawPin { pin: "PB13", signal: "CH1", af: Some(3) },
            RawPin { pin: "PC12", signal: "CH2", af: Some(3) },
            RawPin { pin: "PC4", signal: "ETR", af: Some(3) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "LPUART1", address: 0x44002400, block: Some("LPUART"), pins: &[
            RawPin { pin: "PA10", signal: "RX", af: Some(3) },
            RawPin { pin: "PA11", signal: "CTS", af: Some(3) },
            RawPin { pin: "PA12", signal: "DE", af: Some(3) },
            RawPin { pin: "PA12", signal: "RTS", af: Some(3) },
            RawPin { pin: "PA2", signal: "TX", af: Some(3) },
            RawPin { pin: "PA9", signal: "TX", af: Some(3) },
            RawPin { pin: "PB13", signal: "RX", af: Some(8) },
            RawPin { pin: "PB3", signal: "TX", af: Some(8) },
            RawPin { pin: "PB6", signal: "TX", af: Some(8) },
            RawPin { pin: "PB7", signal: "RX", af: Some(8) },
            RawPin { pin: "PC3", signal: "TX", af: Some(3) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "OCTOSPI1", address: 0x47001400, block: Some("OCTOSPI"), pins: &[
            RawPin { pin: "PA1", signal: "DQS", af: Some(6) },
            RawPin { pin: "PA1", signal: "IO3", af: Some(9) },
            RawPin { pin: "PA15", signal: "NCS", af: Some(9) },
            RawPin { pin: "PA3", signal: "CLK", af: Some(3) },
            RawPin { pin: "PA6", signal: "IO3", af: Some(6) },
            RawPin { pin: "PA7", signal: "IO2", af: Some(10) },
            RawPin { pin: "PB0", signal: "IO1", af: Some(6) },
            RawPin { pin: "PB1", signal: "IO0", af: Some(6) },
            RawPin { pin: "PB10", signal: "NCS", af: Some(9) },
            RawPin { pin: "PB12", signal: "NCLK", af: Some(3) },
            RawPin { pin: "PB15", signal: "CLK", af: Some(10) },
            RawPin { pin: "PB2", signal: "CLK", af: Some(9) },
            RawPin { pin: "PB2", signal: "DQS", af: Some(10) },
            RawPin { pin: "PB4", signal: "CLK", af: Some(3) },
            RawPin { pin: "PB5", signal: "NCLK", af: Some(3) },
            RawPin { pin: "PB6", signal: "NCS", af: Some(10) },
            RawPin { pin: "PC0", signal: "IO7", af: Some(10) },
            RawPin { pin: "PC1", signal: "IO4", af: Some(10) },
            RawPin { pin: "PC10", signal: "IO1", af: Some(9) },
            RawPin { pin: "PC11", signal: "NCS", af: Some(9) },
            RawPin { pin: "PC2", signal: "IO2", af: Some(9) },
            RawPin { pin: "PC2", signal: "IO5", af: Some(6) },
            RawPin { pin: "PC3", signal: "IO0", af: Some(9) },
            RawPin { pin: "PC3", signal: "IO6", af: Some(6) },
            RawPin { pin: "PC5", signal: "DQS", af: Some(10) },
            RawPin { pin: "PC6", signal: "IO5", af: Some(11) },
            RawPin { pin: "PC7", signal: "IO6", af: Some(11) },
            RawPin { pin: "PC9", signal: "IO0", af: Some(9) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "PKA", address: 0x420c2000, block: Some("PKA"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "PSSI", address: 0x4202c400, block: Some("PSSI"), pins: &[
            RawPin { pin: "PA10", signal: "D1", af: Some(13) },
            RawPin { pin: "PA15", signal: "D11", af: Some(13) },
            RawPin { pin: "PA4", signal: "DE", af: Some(13) },
            RawPin { pin: "PA5", signal: "D14", af: Some(13) },
            RawPin { pin: "PA6", signal: "PDCK", af: Some(13) },
            RawPin { pin: "PA8", signal: "D3", af: Some(13) },
            RawPin { pin: "PA9", signal: "D0", af: Some(13) },
            RawPin { pin: "PB15", signal: "D2", af: Some(13) },
            RawPin { pin: "PB4", signal: "D7", af: Some(13) },
            RawPin { pin: "PB5", signal: "D10", af: Some(13) },
            RawPin { pin: "PB6", signal: "D5", af: Some(13) },
            RawPin { pin: "PB7", signal: "RDY", af: Some(13) },
            RawPin { pin: "PB8", signal: "D6", af: Some(13) },
            RawPin { pin: "PC10", signal: "D8", af: Some(13) },
            RawPin { pin: "PC11", signal: "D4", af: Some(13) },
            RawPin { pin: "PC12", signal: "D9", af: Some(13) },
            RawPin { pin: "PC5", signal: "D15", af: Some(4) },
            RawPin { pin: "PC6", signal: "D0", af: Some(13) },
            RawPin { pin: "PC7", signal: "D1", af: Some(13) },
            RawPin { pin: "PC8", signal: "D2", af: Some(13) },
            RawPin { pin: "PC9", signal: "D3", af: Some(13) },
            RawPin { pin: "PD2", signal: "D11", af: Some(13) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "PWR", address: 0x44020800, block: Some("PWR"), pins: &[
            RawPin { pin: "PA0", signal: "WKUP1", af: None },
            RawPin { pin: "PA2", signal: "WKUP2", af: None },
            RawPin { pin: "PB15", signal: "PVD_IN", af: None },
            RawPin { pin: "PB7", signal: "WKUP5", af: None },
            RawPin { pin: "PC1", signal: "WKUP6", af: None },
            RawPin { pin: "PC13", signal: "WKUP4", af: None },
            RawPin { pin: "PC2", signal: "CSLEEP", af: Some(0) },
            RawPin { pin: "PC3", signal: "CSTOP", af: Some(0) },
            RawPin { pin: "PD2", signal: "WKUP7", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "RAMCFG", address: 0x40026000, block: Some("RAMCFG"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "RCC", address: 0x44020c00, block: Some("RCC"), pins: &[
            RawPin { pin: "PA8", signal: "MCO_1", af: Some(0) },
            RawPin { pin: "PB2", signal: "LSCO", af: None },
            RawPin { pin: "PC14", signal: "OSC32_IN", af: None },
            RawPin { pin: "PC15", signal: "OSC32_OUT", af: None },
            RawPin { pin: "PC9", signal: "MCO_2", af: Some(0) },
            RawPin { pin: "PH0", signal: "OSC_IN", af: None },
            RawPin { pin: "PH1", signal: "OSC_OUT", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "RNG", address: 0x420c0800, block: Some("RNG"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "RTC", address: 0x44007800, block: Some("RTC"), pins: &[
            RawPin { pin: "PB15", signal: "REFIN", af: Some(0) },
            RawPin { pin: "PB2", signal: "OUT2", af: Some(0) },
            RawPin { pin: "PC13", signal: "OUT1", af: None },
            RawPin { pin: "PC13", signal: "TS", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SDMMC1", address: 0x46008000, block: Some("SDMMC"), pins: &[
            RawPin { pin: "PA10", signal: "D0", af: Some(12) },
            RawPin { pin: "PB13", signal: "D0", af: Some(12) },
            RawPin { pin: "PB2", signal: "CMD", af: Some(12) },
            RawPin { pin: "PB8", signal: "CKIN", af: Some(7) },
            RawPin { pin: "PB8", signal: "D4", af: Some(12) },
            RawPin { pin: "PC10", signal: "D2", af: Some(12) },
            RawPin { pin: "PC11", signal: "D3", af: Some(12) },
            RawPin { pin: "PC12", signal: "CK", af: Some(12) },
            RawPin { pin: "PC6", signal: "D0DIR", af: Some(8) },
            RawPin { pin: "PC6", signal: "D6", af: Some(12) },
            RawPin { pin: "PC7", signal: "D123DIR", af: Some(8) },
            RawPin { pin: "PC7", signal: "D7", af: Some(12) },
            RawPin { pin: "PC8", signal: "D0", af: Some(12) },
            RawPin { pin: "PC9", signal: "D1", af: Some(12) },
            RawPin { pin: "PD2", signal: "CMD", af: Some(12) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SPI1", address: 0x40013000, block: Some("SPI"), pins: &[
            RawPin { pin: "PA15", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA15", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA4", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA4", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA5", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PA5", signal: "SCK", af: Some(5) },
            RawPin { pin: "PA6", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PA6", signal: "MISO", af: Some(5) },
            RawPin { pin: "PA7", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PA7", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PA8", signal: "RDY", af: Some(5) },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: Some(6) },
            RawPin { pin: "PB15", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PB2", signal: "RDY", af: Some(4) },
            RawPin { pin: "PB3", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PB3", signal: "SCK", af: Some(5) },
            RawPin { pin: "PB4", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PB4", signal: "MISO", af: Some(5) },
            RawPin { pin: "PB5", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PB5", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PC4", signal: "I2S_MCK", af: Some(5) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SPI2", address: 0x40003800, block: Some("SPI"), pins: &[
            RawPin { pin: "PA11", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA11", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA12", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PA12", signal: "SCK", af: Some(5) },
            RawPin { pin: "PA3", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PA3", signal: "NSS", af: Some(5) },
            RawPin { pin: "PA9", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PA9", signal: "SCK", af: Some(5) },
            RawPin { pin: "PB1", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PB1", signal: "NSS", af: Some(5) },
            RawPin { pin: "PB10", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PB10", signal: "SCK", af: Some(5) },
            RawPin { pin: "PB12", signal: "I2S_WS", af: Some(5) },
            RawPin { pin: "PB12", signal: "NSS", af: Some(5) },
            RawPin { pin: "PB13", signal: "I2S_CK", af: Some(5) },
            RawPin { pin: "PB13", signal: "SCK", af: Some(5) },
            RawPin { pin: "PB14", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PB14", signal: "MISO", af: Some(5) },
            RawPin { pin: "PB15", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PB15", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PB2", signal: "I2S_CK", af: Some(6) },
            RawPin { pin: "PB2", signal: "SCK", af: Some(6) },
            RawPin { pin: "PB4", signal: "I2S_WS", af: Some(7) },
            RawPin { pin: "PB4", signal: "NSS", af: Some(7) },
            RawPin { pin: "PC0", signal: "RDY", af: Some(7) },
            RawPin { pin: "PC1", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PC1", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PC2", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PC2", signal: "MISO", af: Some(5) },
            RawPin { pin: "PC3", signal: "I2S_SDO", af: Some(5) },
            RawPin { pin: "PC3", signal: "MOSI", af: Some(5) },
            RawPin { pin: "PC6", signal: "I2S_MCK", af: Some(5) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SPI3", address: 0x40003c00, block: Some("SPI"), pins: &[
            RawPin { pin: "PA0", signal: "RDY", af: Some(6) },
            RawPin { pin: "PA15", signal: "I2S_WS", af: Some(6) },
            RawPin { pin: "PA15", signal: "NSS", af: Some(6) },
            RawPin { pin: "PA3", signal: "I2S_SDO", af: Some(6) },
            RawPin { pin: "PA3", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PA4", signal: "I2S_SDO", af: Some(4) },
            RawPin { pin: "PA4", signal: "I2S_WS", af: Some(6) },
            RawPin { pin: "PA4", signal: "MOSI", af: Some(4) },
            RawPin { pin: "PA4", signal: "NSS", af: Some(6) },
            RawPin { pin: "PB0", signal: "I2S_SDI", af: Some(5) },
            RawPin { pin: "PB0", signal: "MISO", af: Some(5) },
            RawPin { pin: "PB1", signal: "SCK", af: Some(4) },
            RawPin { pin: "PB2", signal: "I2S_SDO", af: Some(7) },
            RawPin { pin: "PB2", signal: "MOSI", af: Some(7) },
            RawPin { pin: "PB3", signal: "I2S_CK", af: Some(6) },
            RawPin { pin: "PB3", signal: "SCK", af: Some(6) },
            RawPin { pin: "PB4", signal: "I2S_SDI", af: Some(6) },
            RawPin { pin: "PB4", signal: "MISO", af: Some(6) },
            RawPin { pin: "PB5", signal: "I2S_SDO", af: Some(7) },
            RawPin { pin: "PB5", signal: "MOSI", af: Some(7) },
            RawPin { pin: "PB8", signal: "I2S_WS", af: Some(6) },
            RawPin { pin: "PB8", signal: "NSS", af: Some(6) },
            RawPin { pin: "PC10", signal: "I2S_CK", af: Some(6) },
            RawPin { pin: "PC10", signal: "SCK", af: Some(6) },
            RawPin { pin: "PC11", signal: "I2S_SDI", af: Some(6) },
            RawPin { pin: "PC11", signal: "MISO", af: Some(6) },
            RawPin { pin: "PC12", signal: "I2S_SDO", af: Some(6) },
            RawPin { pin: "PC12", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PC7", signal: "I2S_MCK", af: Some(6) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SPI4", address: 0x40014c00, block: Some("SPI"), pins: &[
            RawPin { pin: "PA0", signal: "SCK", af: Some(5) },
            RawPin { pin: "PA8", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PB7", signal: "MISO", af: Some(5) },
            RawPin { pin: "PB8", signal: "RDY", af: Some(5) },
            RawPin { pin: "PC0", signal: "MISO", af: Some(6) },
            RawPin { pin: "PC1", signal: "MOSI", af: Some(6) },
            RawPin { pin: "PC5", signal: "SCK", af: Some(6) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "SYSCFG", address: 0x44000400, block: Some("SYSCFG"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "TAMP", address: 0x44007c00, block: Some("TAMP"), pins: &[
            RawPin { pin: "PA0", signal: "IN2", af: None },
            RawPin { pin: "PA0", signal: "OUT1", af: None },
            RawPin { pin: "PA1", signal: "IN5", af: None },
            RawPin { pin: "PA1", signal: "OUT4", af: None },
            RawPin { pin: "PA2", signal: "IN4", af: None },
            RawPin { pin: "PA2", signal: "OUT3", af: None },
            RawPin { pin: "PC1", signal: "IN3", af: None },
            RawPin { pin: "PC1", signal: "OUT5", af: None },
            RawPin { pin: "PC13", signal: "IN1", af: None },
            RawPin { pin: "PC13", signal: "OUT2", af: None },
            RawPin { pin: "PC13", signal: "OUT3", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM1", address: 0x40012c00, block: Some("TIM_ADV"), pins: &[
            RawPin { pin: "PA10", signal: "CH3", af: Some(1) },
            RawPin { pin: "PA11", signal: "CH4", af: Some(1) },
            RawPin { pin: "PA12", signal: "ETR", af: Some(1) },
            RawPin { pin: "PA6", signal: "BKIN", af: Some(1) },
            RawPin { pin: "PA7", signal: "CH1N", af: Some(1) },
            RawPin { pin: "PA8", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA9", signal: "CH2", af: Some(1) },
            RawPin { pin: "PB0", signal: "CH2N", af: Some(1) },
            RawPin { pin: "PB1", signal: "CH3N", af: Some(1) },
            RawPin { pin: "PB12", signal: "BKIN", af: Some(1) },
            RawPin { pin: "PB13", signal: "CH1N", af: Some(1) },
            RawPin { pin: "PB14", signal: "CH2N", af: Some(1) },
            RawPin { pin: "PB15", signal: "CH3N", af: Some(1) },
            RawPin { pin: "PC5", signal: "CH4N", af: Some(1) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM12", address: 0x40001800, block: Some("TIM_2CH"), pins: &[
            RawPin { pin: "PB14", signal: "CH1", af: Some(2) },
            RawPin { pin: "PB15", signal: "CH2", af: Some(2) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM15", address: 0x40014000, block: Some("TIM_2CH_CMP"), pins: &[
            RawPin { pin: "PA0", signal: "BKIN", af: Some(4) },
            RawPin { pin: "PA1", signal: "CH1N", af: Some(4) },
            RawPin { pin: "PA2", signal: "CH1", af: Some(4) },
            RawPin { pin: "PA3", signal: "CH2", af: Some(4) },
            RawPin { pin: "PC12", signal: "CH1", af: Some(2) },
            RawPin { pin: "PD2", signal: "BKIN", af: Some(4) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM2", address: 0x40000000, block: Some("TIM_GP32"), pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA0", signal: "ETR", af: Some(14) },
            RawPin { pin: "PA1", signal: "CH2", af: Some(1) },
            RawPin { pin: "PA15", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA15", signal: "ETR", af: Some(14) },
            RawPin { pin: "PA2", signal: "CH3", af: Some(1) },
            RawPin { pin: "PA3", signal: "CH4", af: Some(1) },
            RawPin { pin: "PA5", signal: "CH1", af: Some(1) },
            RawPin { pin: "PA5", signal: "ETR", af: Some(14) },
            RawPin { pin: "PB10", signal: "CH3", af: Some(1) },
            RawPin { pin: "PB3", signal: "CH2", af: Some(1) },
            RawPin { pin: "PC4", signal: "CH4", af: Some(1) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM3", address: 0x40000400, block: Some("TIM_GP16"), pins: &[
            RawPin { pin: "PA6", signal: "CH1", af: Some(2) },
            RawPin { pin: "PA7", signal: "CH2", af: Some(2) },
            RawPin { pin: "PB0", signal: "CH3", af: Some(2) },
            RawPin { pin: "PB1", signal: "CH4", af: Some(2) },
            RawPin { pin: "PB4", signal: "CH1", af: Some(2) },
            RawPin { pin: "PB5", signal: "CH2", af: Some(2) },
            RawPin { pin: "PC6", signal: "CH1", af: Some(2) },
            RawPin { pin: "PC7", signal: "CH2", af: Some(2) },
            RawPin { pin: "PC8", signal: "CH3", af: Some(2) },
            RawPin { pin: "PC9", signal: "CH4", af: Some(2) },
            RawPin { pin: "PD2", signal: "ETR", af: Some(2) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM4", address: 0x40000800, block: Some("TIM_GP16"), pins: &[
            RawPin { pin: "PB6", signal: "CH1", af: Some(2) },
            RawPin { pin: "PB7", signal: "CH2", af: Some(2) },
            RawPin { pin: "PB8", signal: "CH3", af: Some(2) },
            RawPin { pin: "PC2", signal: "CH4", af: Some(2) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM5", address: 0x40000c00, block: Some("TIM_GP32"), pins: &[
            RawPin { pin: "PA0", signal: "CH1", af: Some(2) },
            RawPin { pin: "PA1", signal: "CH2", af: Some(2) },
            RawPin { pin: "PA2", signal: "CH3", af: Some(2) },
            RawPin { pin: "PA3", signal: "CH4", af: Some(2) },
            RawPin { pin: "PA4", signal: "ETR", af: Some(2) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM6", address: 0x40001000, block: Some("TIM_BASIC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM7", address: 0x40001400, block: Some("TIM_BASIC"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "TIM8", address: 0x40013400, block: Some("TIM_ADV"), pins: &[
            RawPin { pin: "PA0", signal: "ETR", af: Some(3) },
            RawPin { pin: "PA5", signal: "CH1N", af: Some(3) },
            RawPin { pin: "PA6", signal: "BKIN", af: Some(3) },
            RawPin { pin: "PA7", signal: "CH1N", af: Some(3) },
            RawPin { pin: "PA8", signal: "BKIN2", af: Some(3) },
            RawPin { pin: "PB0", signal: "CH2N", af: Some(3) },
            RawPin { pin: "PB1", signal: "CH3N", af: Some(3) },
            RawPin { pin: "PB10", signal: "CH1", af: Some(2) },
            RawPin { pin: "PB12", signal: "CH3", af: Some(2) },
            RawPin { pin: "PB13", signal: "CH2", af: Some(2) },
            RawPin { pin: "PB14", signal: "CH2N", af: Some(3) },
            RawPin { pin: "PB15", signal: "CH3N", af: Some(3) },
            RawPin { pin: "PB2", signal: "CH4N", af: Some(3) },
            RawPin { pin: "PC6", signal: "CH1", af: Some(3) },
            RawPin { pin: "PC7", signal: "CH2", af: Some(3) },
            RawPin { pin: "PC8", signal: "CH3", af: Some(3) },
            RawPin { pin: "PC9", signal: "CH4", af: Some(3) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "UART4", address: 0x40004c00, block: Some("USART"), pins: &[
            RawPin { pin: "PA0", signal: "TX", af: Some(8) },
            RawPin { pin: "PA1", signal: "RX", af: Some(8) },
            RawPin { pin: "PA11", signal: "RX", af: Some(6) },
            RawPin { pin: "PA12", signal: "TX", af: Some(6) },
            RawPin { pin: "PA15", signal: "DE", af: Some(8) },
            RawPin { pin: "PA15", signal: "RTS", af: Some(8) },
            RawPin { pin: "PB0", signal: "CTS", af: Some(8) },
            RawPin { pin: "PB14", signal: "DE", af: Some(8) },
            RawPin { pin: "PB14", signal: "RTS", af: Some(8) },
            RawPin { pin: "PB15", signal: "CTS", af: Some(8) },
            RawPin { pin: "PB8", signal: "RX", af: Some(8) },
            RawPin { pin: "PC10", signal: "TX", af: Some(8) },
            RawPin { pin: "PC11", signal: "RX", af: Some(8) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "UART5", address: 0x40005000, block: Some("USART"), pins: &[
            RawPin { pin: "PB12", signal: "RX", af: Some(14) },
            RawPin { pin: "PB13", signal: "TX", af: Some(14) },
            RawPin { pin: "PB15", signal: "RX", af: Some(14) },
            RawPin { pin: "PB3", signal: "TX", af: Some(14) },
            RawPin { pin: "PB5", signal: "RX", af: Some(14) },
            RawPin { pin: "PB6", signal: "TX", af: Some(14) },
            RawPin { pin: "PC12", signal: "TX", af: Some(8) },
            RawPin { pin: "PC8", signal: "DE", af: Some(8) },
            RawPin { pin: "PC8", signal: "RTS", af: Some(8) },
            RawPin { pin: "PC9", signal: "CTS", af: Some(8) },
            RawPin { pin: "PD2", signal: "RX", af: Some(8) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "UCPD1", address: 0x4000dc00, block: Some("UCPD"), pins: &[
            RawPin { pin: "PA10", signal: "FRSTX", af: Some(6) },
            RawPin { pin: "PA9", signal: "DB1", af: None },
            RawPin { pin: "PB12", signal: "FRSTX", af: Some(6) },
            RawPin { pin: "PB13", signal: "CC1", af: None },
            RawPin { pin: "PB14", signal: "CC2", af: None },
            RawPin { pin: "PC9", signal: "DB2", af: None },
        ], triggers: &[
        ] },
        RawPeripheral { name: "UID", address: 0x08fff800, block: Some("UID"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "USART1", address: 0x40013800, block: Some("USART"), pins: &[
            RawPin { pin: "PA10", signal: "RX", af: Some(7) },
            RawPin { pin: "PA11", signal: "CTS", af: Some(7) },
            RawPin { pin: "PA11", signal: "NSS", af: Some(7) },
            RawPin { pin: "PA12", signal: "DE", af: Some(7) },
            RawPin { pin: "PA12", signal: "RTS", af: Some(7) },
            RawPin { pin: "PA15", signal: "TX", af: Some(7) },
            RawPin { pin: "PA8", signal: "CK", af: Some(7) },
            RawPin { pin: "PA9", signal: "TX", af: Some(7) },
            RawPin { pin: "PB14", signal: "TX", af: Some(4) },
            RawPin { pin: "PB15", signal: "RX", af: Some(4) },
            RawPin { pin: "PB6", signal: "TX", af: Some(7) },
            RawPin { pin: "PB7", signal: "RX", af: Some(7) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "USART2", address: 0x40004400, block: Some("USART"), pins: &[
            RawPin { pin: "PA0", signal: "CTS", af: Some(7) },
            RawPin { pin: "PA0", signal: "NSS", af: Some(7) },
            RawPin { pin: "PA1", signal: "DE", af: Some(7) },
            RawPin { pin: "PA1", signal: "RTS", af: Some(7) },
            RawPin { pin: "PA2", signal: "TX", af: Some(7) },
            RawPin { pin: "PA3", signal: "RX", af: Some(7) },
            RawPin { pin: "PA4", signal: "CK", af: Some(7) },
            RawPin { pin: "PB0", signal: "TX", af: Some(7) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "USART3", address: 0x40004800, block: Some("USART"), pins: &[
            RawPin { pin: "PB1", signal: "RX", af: Some(7) },
            RawPin { pin: "PB10", signal: "TX", af: Some(7) },
            RawPin { pin: "PB12", signal: "CK", af: Some(7) },
            RawPin { pin: "PB13", signal: "CTS", af: Some(7) },
            RawPin { pin: "PB13", signal: "NSS", af: Some(7) },
            RawPin { pin: "PB14", signal: "DE", af: Some(7) },
            RawPin { pin: "PB14", signal: "RTS", af: Some(7) },
            RawPin { pin: "PC10", signal: "TX", af: Some(7) },
            RawPin { pin: "PC11", signal: "RX", af: Some(7) },
            RawPin { pin: "PC12", signal: "CK", af: Some(7) },
            RawPin { pin: "PC4", signal: "RX", af: Some(7) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "USART6", address: 0x40006400, block: Some("USART"), pins: &[
            RawPin { pin: "PA1", signal: "CK", af: Some(14) },
            RawPin { pin: "PB5", signal: "TX", af: Some(6) },
            RawPin { pin: "PB6", signal: "RX", af: Some(6) },
            RawPin { pin: "PB7", signal: "CTS", af: Some(6) },
            RawPin { pin: "PB7", signal: "NSS", af: Some(6) },
            RawPin { pin: "PC6", signal: "TX", af: Some(7) },
            RawPin { pin: "PC7", signal: "RX", af: Some(7) },
            RawPin { pin: "PC8", signal: "CK", af: Some(7) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "USB", address: 0x40016000, block: Some("USB"), pins: &[
            RawPin { pin: "PA11", signal: "DM", af: Some(10) },
            RawPin { pin: "PA12", signal: "DP", af: Some(10) },
            RawPin { pin: "PA8", signal: "SOF", af: Some(10) },
        ], triggers: &[
        ] },
        RawPeripheral { name: "USBRAM", address: 0x40016400, block: Some("USBRAM"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "VREFBUF", address: 0x44007400, block: Some("VREFBUF"), pins: &[
        ], triggers: &[
        ] },
        RawPeripheral { name: "WWDG", address: 0x40002c00, block: Some("WWDG"), pins: &[
        ], triggers: &[
        ] },
    ],
};
