//! Extracts peripheral + pin-AF metadata from `stm32-metapac` and emits a
//! Rust source file consumable by the planner. Run once per supported MCU:
//!
//!   cargo run --bin extract --features extract-g474 -- src/mcu_data/g474.rs
//!   cargo run --bin extract --features extract-h523 -- src/mcu_data/h523.rs
//!
//! The generated file defines `pub static RAW: RawMcuData = ...;` against
//! the schema in `peri_planner::mcu_raw`. Generated files are committed.

#[cfg(not(any(feature = "extract-g474", feature = "extract-h523")))]
compile_error!(
    "Enable one of: --features extract-g474, --features extract-h523. \
     Each maps to a single stm32-metapac chip feature."
);

use std::fs;
use std::path::Path;

fn main() {
    let path = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: extract <output-path>");
        std::process::exit(2);
    });

    let m = &stm32_metapac::metadata::METADATA;
    let mut out = String::new();

    out.push_str(&format!(
        "// GENERATED by `cargo run --bin extract` — do not edit by hand.\n\
         // Source: stm32-metapac chip {} ({} family).\n\n",
        m.name, m.family,
    ));
    out.push_str("use crate::mcu_raw::{RawMcuData, RawPeripheral, RawPin};\n\n");

    out.push_str("pub static RAW: RawMcuData = RawMcuData {\n");
    out.push_str(&format!("    name: {:?},\n", m.name));
    out.push_str(&format!("    family: {:?},\n", m.family));
    out.push_str("    peripherals: &[\n");

    let mut peripheral_count = 0;
    let mut pin_count = 0;
    for p in m.peripherals {
        peripheral_count += 1;
        out.push_str(&format!(
            "        RawPeripheral {{ name: {:?}, address: 0x{:08x}, pins: &[\n",
            p.name, p.address,
        ));
        for pin in p.pins {
            pin_count += 1;
            let af = match pin.af {
                Some(n) => format!("Some({})", n),
                None => "None".to_string(),
            };
            out.push_str(&format!(
                "            RawPin {{ pin: {:?}, signal: {:?}, af: {} }},\n",
                pin.pin, pin.signal, af,
            ));
        }
        out.push_str("        ] },\n");
    }
    out.push_str("    ],\n");
    out.push_str("};\n");

    if let Some(parent) = Path::new(&path).parent() {
        fs::create_dir_all(parent).expect("failed to create output directory");
    }
    fs::write(&path, out).expect("failed to write output file");
    println!(
        "wrote {} ({} peripherals, {} pin entries)",
        path, peripheral_count, pin_count,
    );
}
