//! Extracts peripheral + pin-AF metadata from `stm32-metapac` and emits a
//! Rust source file consumable by the planner. Run once per supported MCU:
//!
//!   cargo run --bin extract --features extract-g474 -- src/mcu_data/g474.rs
//!   cargo run --bin extract --features extract-h523 -- src/mcu_data/h523.rs
//!
//! The generated file defines `pub static RAW: RawMcuData = ...;` against
//! the schema in `peri_planner::mcu_raw`. Generated files are committed.

#[cfg(not(feature = "extract"))]
compile_error!(
    "Enable one of the per-chip extract features (e.g. --features extract-g474r, \
     --features extract-h523z). Each maps to a single stm32-metapac chip feature."
);

use std::fs;
use std::path::Path;

fn main() {
    let path = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: extract <output-path>");
        std::process::exit(2);
    });

    let m = &stm32_metapac::metadata::METADATA;
    let mut out = String::new();

    out.push_str(&format!(
        "// GENERATED by `cargo run --bin extract` — do not edit by hand.\n\
         // Source: stm32-metapac chip {} ({} family).\n\n",
        m.name, m.family,
    ));
    // ----- DMA supply: controller -> channel count, and dmamux -> {controllers}.
    use std::collections::{BTreeMap, BTreeSet};
    let mut pool_channels: BTreeMap<&str, u32> = BTreeMap::new();
    let mut mux_to_ctrls: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for ch in m.dma_channels {
        *pool_channels.entry(ch.dma).or_default() += 1;
        if let Some(mux) = ch.dmamux {
            mux_to_ctrls.entry(mux).or_default().insert(ch.dma);
        }
    }

    // Import only the types this chip actually uses, so empty families don't
    // emit unused-import warnings.
    let has_triggers = m.peripherals.iter().any(|p| !p.triggers.is_empty());
    let has_dma_legs = m.peripherals.iter().any(|p| !p.dma_channels.is_empty());
    let has_pools = !pool_channels.is_empty();
    let mut imports = vec!["RawMcuData", "RawPeripheral", "RawPin"];
    if has_triggers {
        imports.push("RawTrigger");
    }
    if has_dma_legs {
        imports.push("RawDmaLeg");
    }
    if has_pools {
        imports.push("DmaPoolDef");
    }
    out.push_str(&format!("use crate::mcu_raw::{{{}}};\n\n", imports.join(", ")));

    out.push_str("pub static RAW: RawMcuData = RawMcuData {\n");
    out.push_str(&format!("    name: {:?},\n", m.name));
    out.push_str(&format!("    family: {:?},\n", m.family));
    out.push_str("    peripherals: &[\n");

    let mut peripheral_count = 0;
    let mut pin_count = 0;
    let mut trigger_count = 0;
    let mut dma_leg_count = 0;
    for p in m.peripherals {
        peripheral_count += 1;
        let block = match &p.registers {
            Some(r) => format!("Some({:?})", r.block),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "        RawPeripheral {{ name: {:?}, address: 0x{:08x}, block: {}, pins: &[\n",
            p.name, p.address, block,
        ));
        for pin in p.pins {
            pin_count += 1;
            let af = match pin.af {
                Some(n) => format!("Some({})", n),
                None => "None".to_string(),
            };
            out.push_str(&format!(
                "            RawPin {{ pin: {:?}, signal: {:?}, af: {} }},\n",
                pin.pin, pin.signal, af,
            ));
        }
        out.push_str("        ], triggers: &[\n");
        for t in p.triggers {
            trigger_count += 1;
            out.push_str(&format!(
                "            RawTrigger {{ signal: {:?}, source: {:?} }},\n",
                t.signal, t.source,
            ));
        }
        // DMA legs: normalize demand into signal -> set of allowed controller
        // pools (collapsing the DMAMUX / named / fixed models). Skip a signal
        // whose pools don't resolve — it carries no capacity info.
        out.push_str("        ], dma: &[\n");
        let mut by_signal: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
        for d in p.dma_channels {
            let pools = by_signal.entry(d.signal).or_default();
            if let Some(ctrl) = d.dma {
                pools.insert(ctrl); // named-controller model (C5/H5 GPDMA/LPDMA)
            } else if let Some(mux) = d.dmamux {
                if let Some(ctrls) = mux_to_ctrls.get(mux) {
                    pools.extend(ctrls.iter().copied()); // DMAMUX fan-out (G4)
                }
            } else if let Some(chan) = d.channel {
                if let Some(ctrl) = chan.split('_').next() {
                    pools.insert(ctrl); // fixed-channel model: "DMA1_CH5" -> "DMA1"
                }
            }
        }
        for (signal, pools) in &by_signal {
            if pools.is_empty() {
                continue;
            }
            dma_leg_count += 1;
            let list: Vec<String> = pools.iter().map(|c| format!("{:?}", c)).collect();
            out.push_str(&format!(
                "            RawDmaLeg {{ signal: {:?}, pools: &[{}] }},\n",
                signal,
                list.join(", "),
            ));
        }
        out.push_str("        ] },\n");
    }
    out.push_str("    ],\n");
    out.push_str("    dma_pools: &[\n");
    for (name, count) in &pool_channels {
        out.push_str(&format!(
            "        DmaPoolDef {{ name: {:?}, channels: {} }},\n",
            name, count,
        ));
    }
    out.push_str("    ],\n");
    out.push_str("};\n");

    if let Some(parent) = Path::new(&path).parent() {
        fs::create_dir_all(parent).expect("failed to create output directory");
    }
    fs::write(&path, out).expect("failed to write output file");
    println!(
        "wrote {} ({} peripherals, {} pin entries, {} triggers, {} dma legs, {} pools)",
        path, peripheral_count, pin_count, trigger_count, dma_leg_count, pool_channels.len(),
    );
}
