//! Extracts peripheral + pin-AF metadata from `stm32-metapac` and emits a
//! Rust source file consumable by the planner. Run once per supported MCU:
//!
//!   cargo run --bin extract --features extract-g474 -- src/mcu_data/g474.rs
//!   cargo run --bin extract --features extract-h523 -- src/mcu_data/h523.rs
//!
//! The generated file defines `pub static RAW: RawMcuData = ...;` against
//! the schema in `peri_planner::mcu_raw`. Generated files are committed.
//!
//! 2nd arg = the stm32-data chips dir. REQUIRED for chips metapac carries no DMA
//! for (the STM32C5 families — metapac-gen drops it); their DMA pools + legs are
//! sourced from that chip's JSON instead (see [`json_dma`]). Omitting it for a C5
//! chip is a hard error (never a silent empty-DMA descriptor). Ignored for G4/H5
//! (metapac supplies their DMA):
//!
//!   cargo run --bin extract --features extract-c531r -- \
//!       src/mcu_data/c531r.rs ~/my_projects/stm32-data/build/data/chips

#[cfg(not(feature = "extract"))]
compile_error!(
    "Enable one of the per-chip extract features (e.g. --features extract-g474r, \
     --features extract-h523z). Each maps to a single stm32-metapac chip feature."
);

#[path = "json_dma.rs"]
mod json_dma;

use std::fs;
use std::path::Path;

fn main() {
    let path = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: extract <output-path>");
        std::process::exit(2);
    });

    let m = &stm32_metapac::metadata::METADATA;
    let mut out = String::new();

    // ----- DMA model (pools + per-peripheral signal→pools), built OWNED so it
    // can come from metapac or, for families metapac omits DMA for (STM32C5),
    // the chip JSON named via the optional 2nd arg.
    use std::collections::{BTreeMap, BTreeSet};
    let mut pools: BTreeMap<String, u32> = BTreeMap::new();
    let mut mux_to_ctrls: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for ch in m.dma_channels {
        *pools.entry(ch.dma.to_string()).or_default() += 1;
        if let Some(mux) = ch.dmamux {
            mux_to_ctrls.entry(mux.to_string()).or_default().insert(ch.dma.to_string());
        }
    }
    let mut legs_by_peri: BTreeMap<String, BTreeMap<String, BTreeSet<String>>> = BTreeMap::new();
    for p in m.peripherals {
        let by_signal = legs_by_peri.entry(p.name.to_string()).or_default();
        for d in p.dma_channels {
            let sp = by_signal.entry(d.signal.to_string()).or_default();
            if let Some(ctrl) = d.dma {
                sp.insert(ctrl.to_string());
            } else if let Some(mux) = d.dmamux {
                if let Some(ctrls) = mux_to_ctrls.get(mux) {
                    sp.extend(ctrls.iter().cloned());
                }
            } else if let Some(chan) = d.channel {
                if let Some(ctrl) = chan.split('_').next() {
                    sp.insert(ctrl.to_string());
                }
            }
        }
    }
    // metapac-gen drops STM32C5 DMA. When metapac carries none, sourcing it from
    // the chip JSON is MANDATORY (not best-effort) — silently emitting an empty
    // DMA model would regress the descriptor — so the chips-dir arg is required
    // here and the load must succeed; otherwise we fail loudly.
    let mut dma_note = String::new();
    if m.dma_channels.is_empty() {
        let dir = std::env::args().nth(2).unwrap_or_else(|| {
            eprintln!(
                "error: {} carries no metapac DMA (a C5 family) — pass the stm32-data chips dir \
                 as the 2nd arg so DMA can be sourced from the chip JSON.",
                m.name,
            );
            std::process::exit(2);
        });
        let v = json_dma::load_for_chip(&dir, m.name).unwrap_or_else(|| {
            eprintln!("error: no parseable chip JSON matching {} under {}", m.name, dir);
            std::process::exit(2);
        });
        let cd = json_dma::extract(&v);
        pools = cd.pools;
        legs_by_peri = cd.legs;
        dma_note = "; DMA from stm32-data chip JSON".to_string();
    }

    out.push_str(&format!(
        "// GENERATED by `cargo run --bin extract` — do not edit by hand.\n\
         // Source: stm32-metapac chip {} ({} family){}.\n\n",
        m.name, m.family, dma_note,
    ));

    // Import only the types this chip actually uses, so empty families don't
    // emit unused-import warnings.
    let has_triggers = m.peripherals.iter().any(|p| !p.triggers.is_empty());
    let has_dma_legs = legs_by_peri.values().any(|s| s.values().any(|p| !p.is_empty()));
    let has_pools = !pools.is_empty();
    let mut imports = vec!["RawMcuData", "RawPeripheral", "RawPin"];
    if has_triggers {
        imports.push("RawTrigger");
    }
    if has_dma_legs {
        imports.push("RawDmaLeg");
    }
    if has_pools {
        imports.push("DmaPoolDef");
    }
    out.push_str(&format!("use crate::mcu_raw::{{{}}};\n\n", imports.join(", ")));

    out.push_str("pub static RAW: RawMcuData = RawMcuData {\n");
    out.push_str(&format!("    name: {:?},\n", m.name));
    out.push_str(&format!("    family: {:?},\n", m.family));
    out.push_str("    peripherals: &[\n");

    let mut peripheral_count = 0;
    let mut pin_count = 0;
    let mut trigger_count = 0;
    let mut dma_leg_count = 0;
    for p in m.peripherals {
        peripheral_count += 1;
        let block = match &p.registers {
            Some(r) => format!("Some({:?})", r.block),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "        RawPeripheral {{ name: {:?}, address: 0x{:08x}, block: {}, pins: &[\n",
            p.name, p.address, block,
        ));
        for pin in p.pins {
            pin_count += 1;
            let af = match pin.af {
                Some(n) => format!("Some({})", n),
                None => "None".to_string(),
            };
            out.push_str(&format!(
                "            RawPin {{ pin: {:?}, signal: {:?}, af: {} }},\n",
                pin.pin, pin.signal, af,
            ));
        }
        out.push_str("        ], triggers: &[\n");
        for t in p.triggers {
            trigger_count += 1;
            out.push_str(&format!(
                "            RawTrigger {{ signal: {:?}, source: {:?} }},\n",
                t.signal, t.source,
            ));
        }
        // DMA legs: normalize demand into signal -> set of allowed controller
        // pools (collapsing the DMAMUX / named / fixed models). Skip a signal
        // whose pools don't resolve — it carries no capacity info.
        out.push_str("        ], dma: &[\n");
        if let Some(by_signal) = legs_by_peri.get(p.name) {
            for (signal, sig_pools) in by_signal {
                if sig_pools.is_empty() {
                    continue;
                }
                dma_leg_count += 1;
                let list: Vec<String> = sig_pools.iter().map(|c| format!("{:?}", c)).collect();
                out.push_str(&format!(
                    "            RawDmaLeg {{ signal: {:?}, pools: &[{}] }},\n",
                    signal,
                    list.join(", "),
                ));
            }
        }
        out.push_str("        ] },\n");
    }
    out.push_str("    ],\n");
    out.push_str("    dma_pools: &[\n");
    for (name, count) in &pools {
        out.push_str(&format!(
            "        DmaPoolDef {{ name: {:?}, channels: {} }},\n",
            name, count,
        ));
    }
    out.push_str("    ],\n");
    out.push_str("};\n");

    if let Some(parent) = Path::new(&path).parent() {
        fs::create_dir_all(parent).expect("failed to create output directory");
    }
    fs::write(&path, out).expect("failed to write output file");
    println!(
        "wrote {} ({} peripherals, {} pin entries, {} triggers, {} dma legs, {} pools)",
        path, peripheral_count, pin_count, trigger_count, dma_leg_count, pools.len(),
    );
}
