//! "Part finder" — a read-only parametric search over the whole-lineup STM32
//! catalog (`crate::catalog`). MCU-agnostic: it ignores the currently selected
//! chip and searches all ~1600 parts. The data is generated by
//! `tools/gen_catalog.rs`; this view is just a form + results table over
//! `catalog::search`.

use crate::catalog::{self, CatalogEntry, SearchQuery};
use crate::select::{self, AssignedPeri, Verdict, Witness};
use eframe::egui;

/// A sortable Part-finder results column.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum SortCol {
    Name,
    Family,
    Package,
    Flash,
    Ram,
    Uart,
    Can,
    Adc,
    TimAdv,
    CompPwm,
    Dma,
    Verify,
}

/// The active results sort (column + direction). Lives in app state so it
/// persists across frames; applied to a collected view of the cached results, so
/// changing the sort never re-runs the lineup solve.
#[derive(Copy, Clone)]
pub struct CatalogSort {
    pub col: SortCol,
    pub asc: bool,
}

impl Default for CatalogSort {
    fn default() -> Self {
        Self { col: SortCol::Name, asc: true }
    }
}

/// Verified-first ordering for the Verify column.
fn verdict_rank(v: Option<Verdict>) -> u8 {
    match v {
        Some(Verdict::Verified) => 3,
        Some(Verdict::BoundsOnly) => 2,
        Some(Verdict::Infeasible) => 1,
        None => 0,
    }
}

/// Compare two result rows on `col`, tie-broken by part name for stability.
fn cmp_col(
    ea: &CatalogEntry,
    va: Option<Verdict>,
    eb: &CatalogEntry,
    vb: Option<Verdict>,
    col: SortCol,
) -> std::cmp::Ordering {
    let primary = match col {
        SortCol::Name => ea.name.cmp(&eb.name),
        SortCol::Family => ea.family.cmp(&eb.family),
        SortCol::Package => ea.packages.first().cmp(&eb.packages.first()),
        SortCol::Flash => ea.flash_kb.cmp(&eb.flash_kb),
        SortCol::Ram => ea.ram_kb.cmp(&eb.ram_kb),
        SortCol::Uart => ea.total_uart().cmp(&eb.total_uart()),
        SortCol::Can => ea.fdcan.cmp(&eb.fdcan),
        SortCol::Adc => ea.adc.cmp(&eb.adc),
        SortCol::TimAdv => ea.tim_adv.cmp(&eb.tim_adv),
        SortCol::CompPwm => ea.comp_pwm_ch.cmp(&eb.comp_pwm_ch),
        SortCol::Dma => ea.dma_pool_total.cmp(&eb.dma_pool_total),
        SortCol::Verify => verdict_rank(va).cmp(&verdict_rank(vb)),
    };
    primary.then_with(|| ea.name.cmp(&eb.name))
}

/// One human-readable line per allocated element, e.g.
/// `USART2: TX=PA2, RX=PA3 (+2ch DMA)` or `OCP: COMP1 → TIM1 BRK` — the
/// witness hover text.
fn witness_text(w: &Witness) -> String {
    w.iter()
        .map(|ap| match ap {
            AssignedPeri::Instance { peri, pins, dma_channels } => {
                let pins = pins
                    .iter()
                    .map(|(role, pin)| format!("{role}={}", pin.name()))
                    .collect::<Vec<_>>()
                    .join(", ");
                let dma = if *dma_channels > 0 {
                    format!(" (+{dma_channels}ch DMA)")
                } else {
                    String::new()
                };
                if pins.is_empty() {
                    format!("{peri}{dma}")
                } else {
                    format!("{peri}: {pins}{dma}")
                }
            }
            AssignedPeri::Ocp { comp, timer, break_input } => match break_input {
                Some(2) => format!("OCP: {comp} → {timer} BRK2"),
                Some(_) => format!("OCP: {comp} → {timer} BRK"),
                None => format!("OCP: {comp} → {timer} break"),
            },
            AssignedPeri::CompPwm { timer, channel, hs, ls } => {
                format!("{timer} CH{channel}: HS={}, LS={}", hs.name(), ls.name())
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Renders the part finder. `demands` are the per-class constraint rows whose
/// allocation is verified against each bridge-reachable part (Tier-2). Returns
/// the NAME of a part the user clicked to open (resolved by the app to a
/// compiled planner or a read-only lineup-descriptor browser).
pub fn show(
    ui: &mut egui::Ui,
    q: &mut SearchQuery,
    demands: &mut [select::DemandInput],
    cache: &mut select::EvalCache,
    sort: &mut CatalogSort,
) -> Option<String> {
    let mut open: Option<String> = None;
    ui.heading("Part finder");
    ui.label(format!(
        "Parametric search across {} STM32 parts in {} families. All numeric \
         fields are minimums; 0 / unchecked = ignore.",
        catalog::CATALOG.len(),
        catalog::families().len(),
    ));
    ui.separator();

    fn num(ui: &mut egui::Ui, label: &str, v: &mut impl egui::emath::Numeric) {
        ui.label(label);
        ui.add(egui::DragValue::new(v).speed(0.25));
    }

    egui::Grid::new("partfinder_filters")
        .num_columns(4)
        .spacing([18.0, 6.0])
        .show(ui, |ui| {
            num(ui, "Min flash (kB)", &mut q.min_flash_kb);
            num(ui, "Min RAM (kB)", &mut q.min_ram_kb);
            ui.end_row();
            num(ui, "Min UART (USART+UART+LP)", &mut q.min_uart);
            num(ui, "Min FDCAN", &mut q.min_fdcan);
            ui.end_row();
            num(ui, "Min SPI", &mut q.min_spi);
            num(ui, "Min I2C", &mut q.min_i2c);
            ui.end_row();
            num(ui, "Min ADC", &mut q.min_adc);
            num(ui, "Min DAC", &mut q.min_dac);
            ui.end_row();
            num(ui, "Min COMP", &mut q.min_comp);
            num(ui, "Min OPAMP", &mut q.min_opamp);
            ui.end_row();
            num(ui, "Min I3C", &mut q.min_i3c);
            num(ui, "Min UCPD", &mut q.min_ucpd);
            ui.end_row();
            num(ui, "Min OctoSPI", &mut q.min_octospi);
            num(ui, "Min DMA ch", &mut q.min_dma_channels);
            ui.end_row();
            num(ui, "Min adv timer", &mut q.min_tim_adv);
            num(ui, "Min compl. PWM ch", &mut q.min_comp_pwm_ch);
            ui.end_row();
        });

    ui.horizontal(|ui| {
        ui.checkbox(&mut q.require_usb, "USB");
        ui.checkbox(&mut q.require_hrtim, "HRTIM");
        ui.checkbox(&mut q.require_sdmmc, "SDMMC");
        ui.checkbox(&mut q.require_fmc, "FMC");
        ui.checkbox(&mut q.require_eth, "ETH")
            .on_hover_text("Ethernet MAC present");
        ui.checkbox(&mut q.require_ocp_capable, "HW OCP")
            .on_hover_text("Comparator + advanced timer (COMP → timer-break over-current capable)");
        ui.separator();
        ui.label("Family:");
        let current = q.family.clone().unwrap_or_else(|| "(any)".to_string());
        egui::ComboBox::from_id_salt("partfinder_family")
            .selected_text(current)
            .show_ui(ui, |ui| {
                if ui.selectable_label(q.family.is_none(), "(any)").clicked() {
                    q.family = None;
                }
                for fam in catalog::families() {
                    if ui
                        .selectable_label(q.family.as_deref() == Some(fam), fam)
                        .clicked()
                    {
                        q.family = Some(fam.to_string());
                    }
                }
            });
        ui.label("Package:");
        let pkg_text = q
            .package_class
            .as_ref()
            .map(|(k, n)| format!("{k}{n}"))
            .unwrap_or_else(|| "(any)".to_string());
        egui::ComboBox::from_id_salt("partfinder_package")
            .selected_text(pkg_text)
            .show_ui(ui, |ui| {
                if ui.selectable_label(q.package_class.is_none(), "(any)").clicked() {
                    q.package_class = None;
                }
                for (k, n) in catalog::package_class_options() {
                    let opt = (k, n);
                    let sel = q.package_class.as_ref() == Some(&opt);
                    if ui.selectable_label(sel, format!("{}{}", opt.0, opt.1)).clicked() {
                        q.package_class = Some(opt);
                    }
                }
            });
        if ui.button("Reset").clicked() {
            *q = SearchQuery::default();
            for d in demands.iter_mut() {
                d.count = 0;
                d.with_dma = false;
            }
        }
    });

    // Constraints to verify: per-class instance count + RX/TX DMA. When any are
    // set, each bridge-reachable result is solved (Tier-2) for a real allocation
    // and tagged verified / infeasible / bounds-only.
    ui.separator();
    ui.label(
        egui::RichText::new("Verify allocation (Tier-2): instances + pins + DMA channels")
            .strong(),
    );
    egui::Grid::new("partfinder_demands")
        .num_columns(4)
        .spacing([14.0, 4.0])
        .show(ui, |ui| {
            ui.label(egui::RichText::new("Peripheral").weak());
            ui.label(egui::RichText::new("Count").weak());
            ui.label(egui::RichText::new("DMA").weak());
            ui.label(egui::RichText::new("Options (extra pins)").weak());
            ui.end_row();
            for d in demands.iter_mut() {
                ui.label(d.label());
                ui.add(egui::DragValue::new(&mut d.count).range(0..=8).speed(0.1));
                // OCP is an internal trip with no DMA — hide its (no-op) toggle.
                if d.supports_dma() {
                    ui.checkbox(&mut d.with_dma, "");
                } else {
                    d.with_dma = false;
                    ui.label("—").on_hover_text("internal routing, no DMA");
                }
                // Optional signal groups (SPI chip-select, USB-PD dead-battery…):
                // each adds its pins to the contention.
                let opts = d.available_options();
                ui.horizontal(|ui| {
                    for &key in &opts {
                        let mut on = d.has_option(key);
                        if ui.checkbox(&mut on, key).changed() {
                            d.set_option(key, on);
                        }
                    }
                });
                ui.end_row();
            }
        });

    let active: Vec<select::Demand> = demands
        .iter()
        .filter(|d| d.count > 0)
        .map(|d| d.to_demand())
        .collect();

    ui.separator();
    // Cached: the whole-lineup Tier-2 solve runs only when the query/demands
    // change, not every frame.
    let results = cache.results(q, demands);
    if active.is_empty() {
        ui.label(format!(
            "{} matching parts — fully-supported parts are clickable (open in Inventory / Pin-AF).",
            results.len()
        ));
    } else {
        let verified = results.iter().filter(|(_, v, _)| *v == Some(Verdict::Verified)).count();
        let bounds = results.iter().filter(|(_, v, _)| *v == Some(Verdict::BoundsOnly)).count();
        ui.label(format!(
            "{} parts pass Tier-1 (>= {} DMA channels, >= {} GPIO pins) — {} allocation-verified \
             (instances+pins+DMA solved), {} bounds-only (counts pass, not fully verified), \
             rest infeasible.",
            results.len(),
            select::total_channel_demand(&active),
            select::pin_demand(&active),
            verified,
            bounds,
        ));
    }

    const CAP: usize = 400;
    egui::ScrollArea::vertical().show(ui, |ui| {
        egui::Grid::new("partfinder_results")
            .striped(true)
            .num_columns(13)
            .spacing([14.0, 2.0])
            .show(ui, |ui| {
                // Clickable headers: click to sort by that column, click again to
                // flip direction. (USB/HRT/ETH is a combined flag cell — not sorted.)
                const HEADERS: &[(&str, Option<SortCol>)] = &[
                    ("Part", Some(SortCol::Name)),
                    ("Family", Some(SortCol::Family)),
                    ("Package", Some(SortCol::Package)),
                    ("Flash", Some(SortCol::Flash)),
                    ("RAM", Some(SortCol::Ram)),
                    ("UART", Some(SortCol::Uart)),
                    ("CAN", Some(SortCol::Can)),
                    ("ADC/DAC/COMP", Some(SortCol::Adc)),
                    ("TIM (adv)", Some(SortCol::TimAdv)),
                    ("±PWM", Some(SortCol::CompPwm)),
                    ("USB/HRT/ETH", None),
                    ("DMA", Some(SortCol::Dma)),
                    ("Verify", Some(SortCol::Verify)),
                ];
                for (label, col) in HEADERS {
                    match col {
                        Some(c) => {
                            let arrow = if sort.col == *c {
                                if sort.asc { " ▲" } else { " ▼" }
                            } else {
                                ""
                            };
                            let btn = egui::Button::new(
                                egui::RichText::new(format!("{label}{arrow}")).strong(),
                            )
                            .frame(false);
                            if ui.add(btn).on_hover_text("sort").clicked() {
                                if sort.col == *c {
                                    sort.asc = !sort.asc;
                                } else {
                                    *sort = CatalogSort { col: *c, asc: true };
                                }
                            }
                        }
                        None => {
                            ui.strong(*label);
                        }
                    }
                }
                ui.end_row();

                // Sort a collected view of the cached results (never mutates the
                // cache, so re-sorting doesn't re-run the lineup solve).
                let mut rows: Vec<&select::Row> = results.iter().collect();
                rows.sort_by(|a, b| {
                    let ord = cmp_col(a.0, a.1, b.0, b.1, sort.col);
                    if sort.asc { ord } else { ord.reverse() }
                });
                for (e, verdict, witness) in rows.into_iter().take(CAP) {
                    // Every part is clickable now: a compiled part opens its full
                    // planner, any other opens a read-only lineup-descriptor
                    // browser (Inventory / Pin-AF). The pinout is package-letter-
                    // keyed (flash-invariant), so a flash variant shows its
                    // package's representative.
                    if ui
                        .selectable_label(false, &e.name)
                        .on_hover_text("Open in Inventory / Pin-AF")
                        .clicked()
                    {
                        open = Some(e.name.clone());
                    }
                    ui.label(&e.family);
                    // Package(s): compact — first + "+N", full list on hover.
                    let pkg_cell = match e.packages.len() {
                        0 => "—".to_string(),
                        1 | 2 => e.packages.join(" / "),
                        n => format!("{} +{}", e.packages[0], n - 1),
                    };
                    ui.label(pkg_cell).on_hover_text(if e.packages.is_empty() {
                        "no package data".to_string()
                    } else {
                        e.packages.join(", ")
                    });
                    ui.label(format!("{} k", e.flash_kb));
                    ui.label(format!("{} k", e.ram_kb));
                    ui.label(e.total_uart().to_string());
                    ui.label(e.fdcan.to_string());
                    ui.label(format!("{}/{}/{}", e.adc, e.dac, e.comp));
                    ui.label(format!("{} ({})", e.tim_total, e.tim_adv));
                    ui.label(e.comp_pwm_ch.to_string())
                        .on_hover_text("Complementary PWM channels (deadtime-capable CHx/CHxN pairs)");
                    ui.label(format!(
                        "{}/{}/{}",
                        if e.has_usb { "Y" } else { "-" },
                        if e.has_hrtim { "Y" } else { "-" },
                        if e.has_eth { "Y" } else { "-" },
                    ));
                    ui.label(e.dma_pool_total.to_string());
                    match verdict {
                        None => {
                            ui.label("");
                        }
                        Some(Verdict::Verified) => {
                            // Hover shows the witness allocation: per peripheral the
                            // chosen instance, each signal's pin, and DMA channels —
                            // what the user needs to actually wire it.
                            let badge = ui
                                .colored_label(egui::Color32::from_rgb(100, 200, 120), "✓ verified");
                            if let Some(w) = witness {
                                badge.on_hover_text(witness_text(w));
                            }
                        }
                        Some(Verdict::Infeasible) => {
                            ui.colored_label(egui::Color32::from_rgb(220, 100, 100), "✗");
                        }
                        Some(Verdict::BoundsOnly) => {
                            ui.colored_label(egui::Color32::from_rgb(210, 180, 80), "? bounds-only")
                                .on_hover_text(
                                    "Passes the count bounds but no full-allocation proof \
                                     (no compiled descriptor, or descriptor missing data the \
                                     part has, e.g. C5 DMA).",
                                );
                        }
                    }
                    ui.end_row();
                }
            });
        if results.len() > CAP {
            ui.label(format!(
                "... and {} more — refine the filter to narrow down.",
                results.len() - CAP
            ));
        }
    });

    open
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cmp::Ordering;

    #[test]
    fn cmp_col_uses_the_right_field_and_tie_breaks_by_name() {
        let a = &catalog::CATALOG[0];
        let b = &catalog::CATALOG[1];
        // Numeric columns compare the matching field, then tie-break by name.
        assert_eq!(
            cmp_col(a, None, b, None, SortCol::Flash),
            a.flash_kb.cmp(&b.flash_kb).then(a.name.cmp(&b.name))
        );
        assert_eq!(
            cmp_col(a, None, b, None, SortCol::Dma),
            a.dma_pool_total.cmp(&b.dma_pool_total).then(a.name.cmp(&b.name))
        );
        // Verify column ranks Verified above Infeasible.
        assert_eq!(
            cmp_col(a, Some(Verdict::Verified), b, Some(Verdict::Infeasible), SortCol::Verify),
            Ordering::Greater
        );
        // Equal field -> name tie-break (catalog is name-sorted, so a < b).
        assert_eq!(cmp_col(a, None, a, None, SortCol::Flash), Ordering::Equal);
        assert_eq!(cmp_col(a, None, b, None, SortCol::Name), Ordering::Less);
    }
}
