//! Whole-lineup STM32 part catalog for parametric search across the entire
//! STM32 line (~1600 parts), independent of which chips have full pin/AF
//! planning support compiled in.
//!
//! Design: **fully data-driven.** There is exactly one generic
//! [`CatalogEntry`] shape for every MCU and one generic [`SearchQuery`] — no
//! per-MCU code. The data is generated by `tools/gen_catalog.rs` from
//! stm32-data's per-chip JSON and embedded as a single JSON asset, so adding
//! or updating MCUs (a new family, a new stm32-data release) is a data
//! refresh — re-run the generator — not a code change.
//!
//! This is deliberately lighter than `mcu_data`: the catalog carries only
//! the search-relevant projection (memory + peripheral instance counts),
//! not the full pin/AF tables, so it scales to the whole lineup cheaply.

use serde::{Deserialize, Serialize};
use std::sync::LazyLock;

/// One STM32 part. Counts are instance counts (e.g. `usart == 3` means
/// USART1..USART3 exist). All fields are derived mechanically from
/// stm32-data; none are hand-curated per chip.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub name: String,
    pub family: String,
    pub flash_kb: u32,
    pub ram_kb: u32,
    pub usart: u8,
    pub uart: u8,
    pub lpuart: u8,
    pub spi: u8,
    pub i2c: u8,
    pub i3c: u8,
    pub fdcan: u8,
    pub ucpd: u8,
    pub adc: u8,
    pub dac: u8,
    pub comp: u8,
    pub opamp: u8,
    /// Advanced-control timers present (TIM1 / TIM8 / TIM20).
    pub tim_adv: u8,
    /// Total TIMx instances (advanced + general-purpose + basic).
    pub tim_total: u8,
    pub has_usb: bool,
    pub has_hrtim: bool,
    pub octospi: u8,
    pub has_sdmmc: bool,
    pub has_fmc: bool,
}

impl CatalogEntry {
    /// Total asynchronous serial channels (USART + UART + LPUART).
    pub fn total_uart(&self) -> u8 {
        self.usart
            .saturating_add(self.uart)
            .saturating_add(self.lpuart)
    }
}

/// All catalog entries, parsed once (lazily) from the embedded data asset.
pub static CATALOG: LazyLock<Vec<CatalogEntry>> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../assets/catalog.json"))
        .expect("assets/catalog.json is malformed — regenerate with `gen_catalog`")
});

/// A parametric query over the catalog. Every numeric field is a *minimum*;
/// `0` / `false` / `None` fields are ignored. Fully generic — no MCU-specific
/// logic, so it works for every family present in the data.
#[derive(Clone, Debug, Default)]
pub struct SearchQuery {
    /// Restrict to a family, e.g. `"STM32G4"` (case-insensitive). `None` = any.
    pub family: Option<String>,
    pub min_flash_kb: u32,
    pub min_ram_kb: u32,
    /// Minimum combined USART + UART + LPUART count.
    pub min_uart: u8,
    pub min_spi: u8,
    pub min_i2c: u8,
    pub min_fdcan: u8,
    pub min_adc: u8,
    pub min_dac: u8,
    pub min_comp: u8,
    pub min_opamp: u8,
    pub require_usb: bool,
    pub require_hrtim: bool,
}

impl SearchQuery {
    pub fn matches(&self, e: &CatalogEntry) -> bool {
        if let Some(f) = &self.family {
            if !e.family.eq_ignore_ascii_case(f) {
                return false;
            }
        }
        e.flash_kb >= self.min_flash_kb
            && e.ram_kb >= self.min_ram_kb
            && e.total_uart() >= self.min_uart
            && e.spi >= self.min_spi
            && e.i2c >= self.min_i2c
            && e.fdcan >= self.min_fdcan
            && e.adc >= self.min_adc
            && e.dac >= self.min_dac
            && e.comp >= self.min_comp
            && e.opamp >= self.min_opamp
            && (!self.require_usb || e.has_usb)
            && (!self.require_hrtim || e.has_hrtim)
    }
}

/// Run a query, returning matching entries sorted by part name.
pub fn search(q: &SearchQuery) -> Vec<&'static CatalogEntry> {
    let mut v: Vec<&CatalogEntry> = CATALOG.iter().filter(|e| q.matches(e)).collect();
    v.sort_by(|a, b| a.name.cmp(&b.name));
    v
}

/// Distinct families present in the catalog, sorted.
pub fn families() -> Vec<&'static str> {
    let mut v: Vec<&str> = CATALOG.iter().map(|e| e.family.as_str()).collect();
    v.sort_unstable();
    v.dedup();
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_populated() {
        assert!(
            CATALOG.len() > 1000,
            "catalog only has {} entries — did you run `gen_catalog`?",
            CATALOG.len()
        );
    }

    #[test]
    fn find_high_io_can_usb_parts() {
        // The motivating query: ">=6 UARTs, >=1 CAN, USB, >=512 kB flash".
        let q = SearchQuery {
            min_uart: 6,
            min_fdcan: 1,
            require_usb: true,
            min_flash_kb: 512,
            ..Default::default()
        };
        let hits = search(&q);
        assert!(!hits.is_empty(), "expected at least one match");
        for e in &hits {
            assert!(e.total_uart() >= 6 && e.fdcan >= 1 && e.has_usb && e.flash_kb >= 512);
        }
        eprintln!(
            "{} parts match (>=6 uart, >=1 fdcan, usb, >=512kB); e.g. {:?}",
            hits.len(),
            hits.iter().take(8).map(|e| e.name.as_str()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn c5_family_present_and_has_analog_fabric() {
        // C5 should be in the catalog (latest stm32-data) and carry the
        // analog/control fabric (DAC + COMP + advanced timer), unlike C0.
        let c5: Vec<_> = CATALOG.iter().filter(|e| e.family == "STM32C5").collect();
        if c5.is_empty() {
            eprintln!("note: no STM32C5 parts in this catalog build (older stm32-data)");
            return;
        }
        assert!(
            c5.iter().any(|e| e.dac >= 1 && e.comp >= 1 && e.tim_adv >= 1),
            "expected at least one C5 part with DAC + COMP + advanced timer"
        );
    }
}
