//! Whole-lineup STM32 part catalog for parametric search across the entire
//! STM32 line (~1600 parts), independent of which chips have full pin/AF
//! planning support compiled in.
//!
//! Design: **fully data-driven.** There is exactly one generic
//! [`CatalogEntry`] shape for every MCU and one generic [`SearchQuery`] — no
//! per-MCU code. The data is generated by `tools/gen_catalog.rs` from
//! stm32-data's per-chip JSON and embedded as a single JSON asset, so adding
//! or updating MCUs (a new family, a new stm32-data release) is a data
//! refresh — re-run the generator — not a code change.
//!
//! This is deliberately lighter than `mcu_data`: the catalog carries only
//! the search-relevant projection (memory + peripheral instance counts),
//! not the full pin/AF tables, so it scales to the whole lineup cheaply.

use serde::{Deserialize, Serialize};
use std::sync::LazyLock;

/// One STM32 part. Counts are instance counts (e.g. `usart == 3` means
/// USART1..USART3 exist). All fields are derived mechanically from
/// stm32-data; none are hand-curated per chip.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub name: String,
    pub family: String,
    pub flash_kb: u32,
    pub ram_kb: u32,
    pub usart: u8,
    pub uart: u8,
    pub lpuart: u8,
    pub spi: u8,
    pub i2c: u8,
    pub i3c: u8,
    pub fdcan: u8,
    pub ucpd: u8,
    pub adc: u8,
    pub dac: u8,
    pub comp: u8,
    pub opamp: u8,
    /// Advanced-control timers present (TIM1 / TIM8 / TIM20).
    pub tim_adv: u8,
    /// Total TIMx instances (advanced + general-purpose + basic).
    pub tim_total: u8,
    /// Distinct complementary-PWM channels — `(timer, CHxN)` pairs across all
    /// timers (advanced TIM1/8/20 + complementary GP TIM15/16/17). Each is a
    /// deadtime-capable high/low output pair: one synchronous-converter
    /// half-bridge. The Tier-1 capacity bound for a "complementary PWM" demand —
    /// a sound necessary upper bound (a channel also needs both pins placeable,
    /// the Tier-2 check), and a useful filter on its own.
    #[serde(default)]
    pub comp_pwm_ch: u8,
    pub has_usb: bool,
    pub has_hrtim: bool,
    pub octospi: u8,
    pub has_sdmmc: bool,
    pub has_fmc: bool,
    /// Total physical DMA channels across all controllers (DMA / GPDMA / BDMA /
    /// MDMA / LPDMA), **deduplicated across cores** — dual-core parts list the
    /// same controllers under each core, so a naive sum double-counts. This is
    /// the Tier-1 capacity bound for "enough DMA streams" queries (a peripheral
    /// stream consumes one channel; the binding DMA constraint is pool size).
    #[serde(default)]
    pub dma_pool_total: u16,
    /// Distinct AF-capable GPIO pins on the package. The Tier-1 pin-capacity
    /// bound: a part can't host more simultaneous peripheral signals than it has
    /// pins (a necessary condition — precise AF-mux contention is a Tier-2 check
    /// on parts with a compiled descriptor).
    #[serde(default)]
    pub gpio_pins: u16,
    /// Datasheet package styles this exact part ships in, e.g. `["LQFP64"]` or
    /// `["LQFP64","UFBGA64"]` (40% of parts offer several). From stm32-data
    /// `packages[].package`, distinct + sorted.
    #[serde(default)]
    pub packages: Vec<String>,
}

impl CatalogEntry {
    /// Total asynchronous serial channels (USART + UART + LPUART).
    pub fn total_uart(&self) -> u8 {
        self.usart
            .saturating_add(self.uart)
            .saturating_add(self.lpuart)
    }

    /// Distinct land-pattern classes `(kind, pin-count)` this part offers, e.g.
    /// `("LQFP", 64)` — marketing suffixes (`_GP`/`_N`) collapse via
    /// [`crate::phys_pinout::package_class`]. The package-filter granularity.
    pub fn package_classes(&self) -> Vec<(String, u16)> {
        let mut v: Vec<(String, u16)> = self
            .packages
            .iter()
            .filter_map(|p| crate::phys_pinout::package_class(p).map(|(k, n)| (k.to_string(), n)))
            .collect();
        v.sort();
        v.dedup();
        v
    }
}

/// All catalog entries, parsed once (lazily) from the embedded data asset.
pub static CATALOG: LazyLock<Vec<CatalogEntry>> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../assets/catalog.json"))
        .expect("assets/catalog.json is malformed — regenerate with `gen_catalog`")
});

/// A parametric query over the catalog. Every numeric field is a *minimum*;
/// `0` / `false` / `None` fields are ignored. Fully generic — no MCU-specific
/// logic, so it works for every family present in the data.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct SearchQuery {
    /// Restrict to a family, e.g. `"STM32G4"` (case-insensitive). `None` = any.
    pub family: Option<String>,
    pub min_flash_kb: u32,
    pub min_ram_kb: u32,
    /// Minimum combined USART + UART + LPUART count.
    pub min_uart: u8,
    pub min_spi: u8,
    pub min_i2c: u8,
    pub min_fdcan: u8,
    pub min_adc: u8,
    pub min_dac: u8,
    pub min_comp: u8,
    pub min_opamp: u8,
    pub min_i3c: u8,
    pub min_ucpd: u8,
    pub min_octospi: u8,
    /// Minimum total physical DMA channels (capacity across all controllers).
    pub min_dma_channels: u16,
    /// Minimum AF-capable GPIO pins (pin-capacity necessary bound).
    pub min_gpio_pins: u16,
    /// Minimum advanced-control timers (TIM1/8/20 — complementary PWM + breaks).
    pub min_tim_adv: u8,
    /// Minimum complementary-PWM channels (deadtime-capable CHx/CHxN pairs).
    pub min_comp_pwm_ch: u8,
    pub require_usb: bool,
    pub require_hrtim: bool,
    pub require_sdmmc: bool,
    pub require_fmc: bool,
    /// Require hardware over-current capability: a comparator AND an advanced
    /// timer present — the necessary condition for a COMP → timer-break OCP path
    /// (the actual routing is a Tier-2 fabric check). A loose, sound Tier-1
    /// filter: any part lacking either definitely can't do hardware OCP.
    pub require_ocp_capable: bool,
    /// Require an offered footprint of this land-pattern class `(kind, pin-count)`,
    /// e.g. `("LQFP", 64)`. `None` = any package.
    pub package_class: Option<(String, u16)>,
}

impl SearchQuery {
    pub fn matches(&self, e: &CatalogEntry) -> bool {
        if let Some(f) = &self.family {
            if !e.family.eq_ignore_ascii_case(f) {
                return false;
            }
        }
        e.flash_kb >= self.min_flash_kb
            && e.ram_kb >= self.min_ram_kb
            && e.total_uart() >= self.min_uart
            && e.spi >= self.min_spi
            && e.i2c >= self.min_i2c
            && e.fdcan >= self.min_fdcan
            && e.adc >= self.min_adc
            && e.dac >= self.min_dac
            && e.comp >= self.min_comp
            && e.opamp >= self.min_opamp
            && e.i3c >= self.min_i3c
            && e.ucpd >= self.min_ucpd
            && e.octospi >= self.min_octospi
            && e.dma_pool_total >= self.min_dma_channels
            && e.gpio_pins >= self.min_gpio_pins
            && e.tim_adv >= self.min_tim_adv
            && e.comp_pwm_ch >= self.min_comp_pwm_ch
            && (!self.require_usb || e.has_usb)
            && (!self.require_hrtim || e.has_hrtim)
            && (!self.require_sdmmc || e.has_sdmmc)
            && (!self.require_fmc || e.has_fmc)
            && (!self.require_ocp_capable || (e.comp >= 1 && e.tim_adv >= 1))
            && self
                .package_class
                .as_ref()
                .is_none_or(|want| e.package_classes().iter().any(|c| c == want))
    }
}

/// Distinct package land-pattern classes present across the catalog, sorted —
/// the option set for a package filter (e.g. `("LQFP", 64)`).
pub fn package_class_options() -> Vec<(String, u16)> {
    let mut v: Vec<(String, u16)> =
        CATALOG.iter().flat_map(|e| e.package_classes()).collect();
    v.sort();
    v.dedup();
    v
}

/// Run a query, returning matching entries sorted by part name.
pub fn search(q: &SearchQuery) -> Vec<&'static CatalogEntry> {
    let mut v: Vec<&CatalogEntry> = CATALOG.iter().filter(|e| q.matches(e)).collect();
    v.sort_by(|a, b| a.name.cmp(&b.name));
    v
}

/// Distinct families present in the catalog, sorted.
pub fn families() -> Vec<&'static str> {
    let mut v: Vec<&str> = CATALOG.iter().map(|e| e.family.as_str()).collect();
    v.sort_unstable();
    v.dedup();
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_populated() {
        assert!(
            CATALOG.len() > 1000,
            "catalog only has {} entries — did you run `gen_catalog`?",
            CATALOG.len()
        );
    }

    #[test]
    fn find_high_io_can_usb_parts() {
        // The motivating query: ">=6 UARTs, >=1 CAN, USB, >=512 kB flash".
        let q = SearchQuery {
            min_uart: 6,
            min_fdcan: 1,
            require_usb: true,
            min_flash_kb: 512,
            ..Default::default()
        };
        let hits = search(&q);
        assert!(!hits.is_empty(), "expected at least one match");
        for e in &hits {
            assert!(e.total_uart() >= 6 && e.fdcan >= 1 && e.has_usb && e.flash_kb >= 512);
        }
        eprintln!(
            "{} parts match (>=6 uart, >=1 fdcan, usb, >=512kB); e.g. {:?}",
            hits.len(),
            hits.iter().take(8).map(|e| e.name.as_str()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn c5_family_present_and_has_analog_fabric() {
        // C5 should be in the catalog (latest stm32-data) and carry the
        // analog/control fabric (DAC + COMP + advanced timer), unlike C0.
        let c5: Vec<_> = CATALOG.iter().filter(|e| e.family == "STM32C5").collect();
        if c5.is_empty() {
            eprintln!("note: no STM32C5 parts in this catalog build (older stm32-data)");
            return;
        }
        assert!(
            c5.iter().any(|e| e.dac >= 1 && e.comp >= 1 && e.tim_adv >= 1),
            "expected at least one C5 part with DAC + COMP + advanced timer"
        );
    }

    #[test]
    fn ocp_capable_and_adv_timer_filters() {
        // Hardware-OCP-capable = comparator AND advanced timer present (the
        // necessary condition for a COMP -> timer-break path).
        let ocp = search(&SearchQuery { require_ocp_capable: true, ..Default::default() });
        assert!(!ocp.is_empty());
        assert!(ocp.iter().all(|e| e.comp >= 1 && e.tim_adv >= 1));
        // The analog-rich power families qualify; it genuinely narrows.
        assert!(ocp.iter().any(|e| e.family == "STM32G4"));
        assert!(ocp.len() < search(&SearchQuery::default()).len());

        // min_tim_adv discriminates on advanced-timer count.
        let adv = search(&SearchQuery { min_tim_adv: 2, ..Default::default() });
        assert!(!adv.is_empty() && adv.iter().all(|e| e.tim_adv >= 2));
    }

    #[test]
    fn dma_pool_total_deduped_and_filters() {
        // Known supply counts (distinct controller channels).
        let g4 = CATALOG
            .iter()
            .find(|e| e.name == "STM32G474RE")
            .expect("STM32G474RE in catalog");
        assert_eq!(g4.dma_pool_total, 16, "G474 = DMA1(8) + DMA2(8)");

        // Dual-core dedup: H745 lists 40 channels under EACH core; the count
        // must be the deduped ~40, never the naive 80 (the A2 bug).
        if let Some(h745) = CATALOG.iter().find(|e| e.name.starts_with("STM32H745")) {
            assert!(
                h745.dma_pool_total <= 48,
                "dual-core {} dma_pool_total={} — channels must be deduped across cores",
                h745.name,
                h745.dma_pool_total,
            );
            assert!(
                h745.dma_pool_total >= 32,
                "{} should still report its real channel count",
                h745.name,
            );
        }

        // Sanity: no part double-counts into an implausible channel count.
        let max = CATALOG.iter().map(|e| e.dma_pool_total).max().unwrap_or(0);
        assert!(max <= 64, "max dma_pool_total={max} looks like a dedup bug");

        // Monotonic: a min_dma_channels bound only narrows, and every hit honors it.
        let base = search(&SearchQuery::default()).len();
        let bounded = search(&SearchQuery { min_dma_channels: 8, ..Default::default() });
        assert!(bounded.len() <= base && !bounded.is_empty());
        assert!(bounded.iter().all(|e| e.dma_pool_total >= 8));
    }

    #[test]
    fn new_filters_narrow_results() {
        let sdmmc = search(&SearchQuery {
            require_sdmmc: true,
            ..Default::default()
        });
        assert!(!sdmmc.is_empty() && sdmmc.iter().all(|e| e.has_sdmmc));

        let octo = search(&SearchQuery {
            min_octospi: 1,
            ..Default::default()
        });
        assert!(!octo.is_empty() && octo.iter().all(|e| e.octospi >= 1));

        // Adding a constraint only narrows the result set (monotonic).
        let base = search(&SearchQuery {
            min_flash_kb: 256,
            ..Default::default()
        })
        .len();
        let tighter = search(&SearchQuery {
            min_flash_kb: 256,
            require_fmc: true,
            ..Default::default()
        })
        .len();
        assert!(tighter <= base && tighter > 0);
    }

    #[test]
    fn parts_carry_package_styles() {
        // Every part should list at least one datasheet package style.
        let missing = CATALOG.iter().filter(|e| e.packages.is_empty()).count();
        assert!(missing == 0, "{missing} parts have no package data — regenerate catalog");
        // A known part: G474RE is LQFP64.
        let g4 = CATALOG.iter().find(|e| e.name == "STM32G474RE").unwrap();
        assert_eq!(g4.package_classes(), vec![("LQFP".to_string(), 64)]);
        // Multi-footprint parts exist (a letter can span QFP + BGA).
        assert!(
            CATALOG.iter().any(|e| e.package_classes().len() > 1),
            "expected at least one multi-footprint part"
        );
    }

    #[test]
    fn package_class_filter_narrows_to_offered_footprint() {
        let opts = package_class_options();
        assert!(!opts.is_empty());
        let want = ("LQFP".to_string(), 64);
        assert!(opts.contains(&want));

        let base = search(&SearchQuery::default()).len();
        let hits = search(&SearchQuery { package_class: Some(want.clone()), ..Default::default() });
        assert!(!hits.is_empty() && hits.len() < base);
        // Every hit genuinely offers an LQFP64-class footprint.
        assert!(hits.iter().all(|e| e.package_classes().contains(&want)));
        // G474RE qualifies; a part with no LQFP64 offering is excluded.
        assert!(hits.iter().any(|e| e.name == "STM32G474RE"));
    }
}
