//! "Part finder" — a read-only parametric search over the whole-lineup STM32
//! catalog (`crate::catalog`). MCU-agnostic: it ignores the currently selected
//! chip and searches all ~1600 parts. The data is generated by
//! `tools/gen_catalog.rs`; this view is just a form + results table over
//! `catalog::search`.

use crate::catalog::{self, SearchQuery};
use crate::mcu::Package;
use eframe::egui;

/// Renders the part finder. Returns the package to jump to if the user clicked
/// a result that maps to a compiled-in part.
pub fn show(ui: &mut egui::Ui, q: &mut SearchQuery) -> Option<Package> {
    let mut jump = None;
    ui.heading("Part finder");
    ui.label(format!(
        "Parametric search across {} STM32 parts in {} families. All numeric \
         fields are minimums; 0 / unchecked = ignore.",
        catalog::CATALOG.len(),
        catalog::families().len(),
    ));
    ui.separator();

    fn num(ui: &mut egui::Ui, label: &str, v: &mut impl egui::emath::Numeric) {
        ui.label(label);
        ui.add(egui::DragValue::new(v).speed(0.25));
    }

    egui::Grid::new("partfinder_filters")
        .num_columns(4)
        .spacing([18.0, 6.0])
        .show(ui, |ui| {
            num(ui, "Min flash (kB)", &mut q.min_flash_kb);
            num(ui, "Min RAM (kB)", &mut q.min_ram_kb);
            ui.end_row();
            num(ui, "Min UART (USART+UART+LP)", &mut q.min_uart);
            num(ui, "Min FDCAN", &mut q.min_fdcan);
            ui.end_row();
            num(ui, "Min SPI", &mut q.min_spi);
            num(ui, "Min I2C", &mut q.min_i2c);
            ui.end_row();
            num(ui, "Min ADC", &mut q.min_adc);
            num(ui, "Min DAC", &mut q.min_dac);
            ui.end_row();
            num(ui, "Min COMP", &mut q.min_comp);
            num(ui, "Min OPAMP", &mut q.min_opamp);
            ui.end_row();
            num(ui, "Min I3C", &mut q.min_i3c);
            num(ui, "Min UCPD", &mut q.min_ucpd);
            ui.end_row();
            num(ui, "Min OctoSPI", &mut q.min_octospi);
            num(ui, "Min DMA ch", &mut q.min_dma_channels);
            ui.end_row();
            num(ui, "Min adv timer", &mut q.min_tim_adv);
            ui.end_row();
        });

    ui.horizontal(|ui| {
        ui.checkbox(&mut q.require_usb, "USB");
        ui.checkbox(&mut q.require_hrtim, "HRTIM");
        ui.checkbox(&mut q.require_sdmmc, "SDMMC");
        ui.checkbox(&mut q.require_fmc, "FMC");
        ui.checkbox(&mut q.require_ocp_capable, "HW OCP")
            .on_hover_text("Comparator + advanced timer (COMP → timer-break over-current capable)");
        ui.separator();
        ui.label("Family:");
        let current = q.family.clone().unwrap_or_else(|| "(any)".to_string());
        egui::ComboBox::from_id_salt("partfinder_family")
            .selected_text(current)
            .show_ui(ui, |ui| {
                if ui.selectable_label(q.family.is_none(), "(any)").clicked() {
                    q.family = None;
                }
                for fam in catalog::families() {
                    if ui
                        .selectable_label(q.family.as_deref() == Some(fam), fam)
                        .clicked()
                    {
                        q.family = Some(fam.to_string());
                    }
                }
            });
        if ui.button("Reset").clicked() {
            *q = SearchQuery::default();
        }
    });

    ui.separator();
    let results = catalog::search(q);
    ui.label(format!(
        "{} matching parts — fully-supported parts are clickable (open in Inventory / Pin-AF).",
        results.len()
    ));

    const CAP: usize = 400;
    egui::ScrollArea::vertical().show(ui, |ui| {
        egui::Grid::new("partfinder_results")
            .striped(true)
            .num_columns(10)
            .spacing([14.0, 2.0])
            .show(ui, |ui| {
                for h in [
                    "Part", "Family", "Flash", "RAM", "UART", "CAN", "ADC/DAC/COMP",
                    "TIM (adv)", "USB/HRTIM", "DMA",
                ] {
                    ui.strong(h);
                }
                ui.end_row();
                for e in results.iter().take(CAP) {
                    // Parts that are compiled in are clickable -> jump to them.
                    match Package::for_chip_name(&e.name) {
                        Some(pkg) => {
                            // The descriptor is keyed on the package letter (pins
                            // are flash-invariant), so a flash variant opens its
                            // package's descriptor — name the target to be honest.
                            if ui
                                .selectable_label(false, &e.name)
                                .on_hover_text(format!(
                                    "Open {} (Inventory / Pin-AF)",
                                    pkg.display_label()
                                ))
                                .clicked()
                            {
                                jump = Some(pkg);
                            }
                        }
                        None => {
                            ui.label(&e.name);
                        }
                    }
                    ui.label(&e.family);
                    ui.label(format!("{} k", e.flash_kb));
                    ui.label(format!("{} k", e.ram_kb));
                    ui.label(e.total_uart().to_string());
                    ui.label(e.fdcan.to_string());
                    ui.label(format!("{}/{}/{}", e.adc, e.dac, e.comp));
                    ui.label(format!("{} ({})", e.tim_total, e.tim_adv));
                    ui.label(format!(
                        "{}/{}",
                        if e.has_usb { "Y" } else { "-" },
                        if e.has_hrtim { "Y" } else { "-" },
                    ));
                    ui.label(e.dma_pool_total.to_string());
                    ui.end_row();
                }
            });
        if results.len() > CAP {
            ui.label(format!(
                "... and {} more — refine the filter to narrow down.",
                results.len() - CAP
            ));
        }
    });

    jump
}
