//! Firmware codegen — turns a [`PinPlan`](crate::pin_plan::PinPlan) into
//! embassy-stm32 scaffold source for the firmware crate. See
//! `docs/firmware-codegen-design.md` (the "generate a board-support *scaffold*,
//! not a full init" stance).
//!
//! This increment emits the **Tier-1 board-support layer**: a generated `Board`
//! struct that names every peripheral instance and pin the plan uses,
//! destructured from embassy's `Peripherals`. It is purely *structural* — no
//! behavioral value can appear — and is the foundation the driver constructors
//! (next increment) build on. The output is a Rust source string; peri-planner
//! itself does not depend on embassy, so codegen is string generation, not
//! compilation.

use crate::pin_plan::{Placement, PinPlan};

/// Peripheral classes whose embassy singleton we bind as a `Board` field.
/// Their pins are bound regardless; analog peripherals (COMP/OPAMP) get pin
/// fields but no instance field (their instances are Tier-2/3 raw access).
const TIER1_INSTANCE_CLASSES: &[&str] =
    &["USART", "UART", "LPUART", "SPI", "I2C", "TIM", "ADC", "DAC", "FDCAN", "HRTIM"];

/// The peripheral class of an instance name, i.e. the name with its trailing
/// instance digits stripped: `"USART2" -> "USART"`, `"I2C1" -> "I2C"`,
/// `"HRTIM1" -> "HRTIM"`.
fn class_of(instance: &str) -> &str {
    instance.trim_end_matches(|c: char| c.is_ascii_digit())
}

fn is_tier1_instance(instance: &str) -> bool {
    TIER1_INSTANCE_CLASSES.contains(&class_of(instance))
}

/// Sanitize a metapac name into a snake_case Rust identifier fragment.
/// Names here are alphanumeric (`USART2`, `CH1`, `IN3`), so this just
/// lowercases; non-alphanumerics (none expected) fold to `_`.
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect()
}

/// Field name for a pin-bearing placement: `{peripheral}_{role}` lowercased,
/// e.g. `usart2_tx`, `tim1_ch1`, `hrtim1_cha1`.
fn pin_field(p: &Placement) -> String {
    format!("{}_{}", ident(&p.signal.peripheral), ident(&p.signal.role))
}

/// Generate the Tier-1 board-support module — a `Board` struct naming every
/// instance and pin the plan uses, plus `Board::take(p)` that destructures the
/// embassy `Peripherals`. Never hand-edited; regenerate from the plan.
pub fn generate_board(plan: &PinPlan) -> String {
    use std::fmt::Write as _;
    let mut s = String::new();

    let _ = writeln!(
        s,
        "// @generated by peri-planner from PinPlan (target {} / {}) — DO NOT EDIT.",
        plan.target.package, plan.target.family
    );
    let _ = writeln!(s, "// Tier-1 board-support scaffold: names every peripheral instance and pin this");
    let _ = writeln!(s, "// design uses. Structural only — behavioral config (baud, dead-time, …) is yours.");
    let _ = writeln!(s, "#![allow(dead_code)]");
    let _ = writeln!(s);
    let _ = writeln!(s, "use embassy_stm32::{{peripherals, Peripherals}};");
    let _ = writeln!(s);

    // Distinct Tier-1 instances, in placement (i.e. sorted) order.
    let mut instances: Vec<&str> = Vec::new();
    for p in &plan.placements {
        let inst = p.signal.peripheral.as_str();
        if is_tier1_instance(inst) && !instances.contains(&inst) {
            instances.push(inst);
        }
    }

    let _ = writeln!(s, "/// Every peripheral instance and pin this design uses, named by function.");
    let _ = writeln!(s, "pub struct Board {{");
    for inst in &instances {
        let _ = writeln!(s, "    pub {}: peripherals::{inst},", ident(inst));
    }
    for p in &plan.placements {
        match p.pin {
            Some(pin) => {
                let _ = writeln!(s, "    pub {}: peripherals::{},", pin_field(p), pin.name());
            }
            None => {
                let _ = writeln!(
                    s,
                    "    // unplaced: {} {} (declared, no pin yet)",
                    p.signal.peripheral, p.signal.role
                );
            }
        }
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);

    let _ = writeln!(s, "impl Board {{");
    let _ = writeln!(s, "    /// Destructure the embassy `Peripherals` into named resources.");
    let _ = writeln!(s, "    pub fn take(p: Peripherals) -> Self {{");
    let _ = writeln!(s, "        Self {{");
    for inst in &instances {
        let _ = writeln!(s, "            {}: p.{inst},", ident(inst));
    }
    for p in &plan.placements {
        if let Some(pin) = p.pin {
            let _ = writeln!(s, "            {}: p.{},", pin_field(p), pin.name());
        }
    }
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");

    s
}

/// One behavioral parameter the pin plan cannot know — a generated `Behavior`
/// field. Adding a routed peripheral adds a hole, so the design and its config
/// can't silently drift (docs/firmware-codegen-design.md §4).
struct Hole {
    name: String,
    ty: &'static str,
    default: &'static str,
    doc: &'static str,
}

/// The behavioral holes implied by the plan's Tier-1 peripherals, in instance
/// order. Derived from the peripheral class + its placements' role kinds.
fn behavior_holes(plan: &PinPlan) -> Vec<Hole> {
    use crate::pin_plan::RoleKind;
    let mut instances: Vec<&str> = Vec::new();
    for p in &plan.placements {
        let inst = p.signal.peripheral.as_str();
        if is_tier1_instance(inst) && !instances.contains(&inst) {
            instances.push(inst);
        }
    }

    let mut holes = Vec::new();
    for inst in instances {
        let id = ident(inst);
        match class_of(inst) {
            "USART" | "UART" | "LPUART" => holes.push(Hole {
                name: format!("{id}_baud"), ty: "u32", default: "115_200", doc: "baud rate",
            }),
            "SPI" => holes.push(Hole {
                name: format!("{id}_freq_hz"), ty: "u32", default: "1_000_000", doc: "SCK frequency (Hz)",
            }),
            "I2C" => holes.push(Hole {
                name: format!("{id}_freq_hz"), ty: "u32", default: "100_000", doc: "bus frequency (Hz)",
            }),
            "FDCAN" => holes.push(Hole {
                name: format!("{id}_bitrate"), ty: "u32", default: "500_000", doc: "nominal bitrate (bps)",
            }),
            "TIM" | "HRTIM" => {
                let pwm = plan.placements.iter().any(|p| {
                    p.signal.peripheral == inst && matches!(p.role_kind, RoleKind::PwmOut { .. })
                });
                if pwm {
                    holes.push(Hole {
                        name: format!("{id}_freq_hz"), ty: "u32", default: "100_000",
                        doc: "PWM switching frequency (Hz)",
                    });
                    let dead_time = plan.placements.iter().any(|p| {
                        p.signal.peripheral == inst
                            && matches!(p.role_kind, RoleKind::PwmOut { dead_time: true, .. })
                    });
                    if dead_time {
                        holes.push(Hole {
                            name: format!("{id}_dead_time_ns"), ty: "u16", default: "0",
                            doc: "complementary dead-time (ns)",
                        });
                    }
                }
            }
            _ => {} // ADC/DAC: no required scalar in v1.
        }
    }
    holes
}

/// Append the behavioral-config contract (`Behavior` struct + `Default`) — the
/// set of holes the user fills, structurally separate from the plan.
fn write_behavior(s: &mut String, plan: &PinPlan) {
    use std::fmt::Write as _;
    let holes = behavior_holes(plan);
    let _ = writeln!(s);
    let _ = writeln!(s, "/// Behavioral configuration you must supply — one field per value the pin");
    let _ = writeln!(s, "/// plan cannot know (it carries no behavioral values by design). Adjust the");
    let _ = writeln!(s, "/// defaults to your converter. Adding a routed peripheral adds a field here,");
    let _ = writeln!(s, "/// so the design and its config can't silently drift.");
    let _ = writeln!(s, "#[derive(Clone, Copy, Debug)]");
    let _ = writeln!(s, "pub struct Behavior {{");
    for h in &holes {
        let _ = writeln!(s, "    /// {}", h.doc);
        let _ = writeln!(s, "    pub {}: {},", h.name, h.ty);
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);
    let _ = writeln!(s, "impl Default for Behavior {{");
    let _ = writeln!(s, "    fn default() -> Self {{");
    let _ = writeln!(s, "        Self {{");
    for h in &holes {
        let _ = writeln!(s, "            {}: {},", h.name, h.default);
    }
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");
}

/// Generate the full Tier-1 firmware scaffold module: the board-support layer
/// (every instance + pin) followed by the behavioral-config contract.
pub fn generate(plan: &PinPlan) -> String {
    let mut s = generate_board(plan);
    write_behavior(&mut s, plan);
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcu_pinout::{OwnedSignal, PinId};
    use crate::pin_plan::{PinOrigin, PinPlan, Placement, RoleKind, Target};

    fn placement(peripheral: &str, role: &str, pin: Option<PinId>) -> Placement {
        Placement {
            signal: OwnedSignal { peripheral: peripheral.into(), role: role.into() },
            pin,
            origin: PinOrigin::Locked,
            af: None,
            role_kind: RoleKind::Gpio,
            dma: None,
            irqs: Vec::new(),
            package_pin: None,
            net: None,
        }
    }

    #[test]
    fn generate_board_names_instances_and_pins() {
        let mut plan = PinPlan::empty(Target { package: "H523RE".into(), family: "H5".into() });
        plan.placements.push(placement("USART1", "TX", Some(PinId { port: 'A', num: 9 })));
        plan.placements.push(placement("USART1", "RX", None)); // declared, unplaced
        let code = generate_board(&plan);

        assert!(code.contains("from PinPlan (target H523RE / H5)"));
        // Instance bound once; pin bound and destructured from `p`.
        assert!(code.contains("pub usart1: peripherals::USART1,"));
        assert!(code.contains("pub usart1_tx: peripherals::PA9,"));
        assert!(code.contains("usart1: p.USART1,"));
        assert!(code.contains("usart1_tx: p.PA9,"));
        // Unplaced signal -> comment, never a bogus field.
        assert!(code.contains("// unplaced: USART1 RX"));
        assert!(!code.contains("usart1_rx: peripherals::"));
    }

    #[test]
    fn analog_peripherals_bind_pins_but_not_instances() {
        // COMP is not a Tier-1 instance class: its pin is bound, instance is not.
        let mut plan = PinPlan::empty(Target { package: "G474R".into(), family: "G4".into() });
        plan.placements.push(placement("COMP1", "INP", Some(PinId { port: 'A', num: 1 })));
        plan.placements.push(placement("ADC1", "IN2", Some(PinId { port: 'A', num: 2 })));
        let code = generate_board(&plan);

        assert!(code.contains("pub comp1_inp: peripherals::PA1,"), "COMP pin bound");
        assert!(!code.contains("pub comp1: peripherals::COMP1,"), "COMP instance NOT bound (Tier-2/3)");
        assert!(code.contains("pub adc1: peripherals::ADC1,"), "ADC instance bound (Tier-1)");
        assert!(code.contains("pub adc1_in2: peripherals::PA2,"));
    }

    #[test]
    fn generate_emits_behavior_contract_holes() {
        let mut plan = PinPlan::empty(Target { package: "G474R".into(), family: "G4".into() });
        plan.placements.push(placement("USART1", "TX", Some(PinId { port: 'A', num: 9 })));
        plan.placements.push(placement("SPI1", "SCK", Some(PinId { port: 'A', num: 5 })));
        // A complementary PWM channel with dead-time -> freq + dead-time holes.
        plan.placements.push(Placement {
            role_kind: RoleKind::PwmOut { complementary: true, dead_time: true, etr: false },
            ..placement("TIM1", "CH1", Some(PinId { port: 'A', num: 8 }))
        });
        let code = generate(&plan);

        // One hole per behavioral value the plan can't know.
        assert!(code.contains("pub usart1_baud: u32,"));
        assert!(code.contains("pub spi1_freq_hz: u32,"));
        assert!(code.contains("pub tim1_freq_hz: u32,"));
        assert!(code.contains("pub tim1_dead_time_ns: u16,"));
        // Defaults wired up.
        assert!(code.contains("usart1_baud: 115_200,"));
        assert!(code.contains("tim1_dead_time_ns: 0,"));
        // Behavior struct present; board layer still emitted above it.
        assert!(code.contains("pub struct Behavior {"));
        assert!(code.contains("pub struct Board {"));
        // No behavioral VALUE ever leaks into the board layer.
        assert!(!code.contains("115_200,\n    pub usart1: peripherals"));
    }

    #[test]
    fn class_of_strips_instance_digits() {
        assert_eq!(class_of("USART2"), "USART");
        assert_eq!(class_of("I2C1"), "I2C");
        assert_eq!(class_of("HRTIM1"), "HRTIM");
        assert!(is_tier1_instance("LPUART1"));
        assert!(!is_tier1_instance("COMP1"));
    }
}
