//! Firmware codegen — turns a [`PinPlan`](crate::pin_plan::PinPlan) into
//! embassy-stm32 scaffold source for the firmware crate. See
//! `docs/firmware-codegen-design.md` (the "generate a board-support *scaffold*,
//! not a full init" stance).
//!
//! This increment emits the **Tier-1 board-support layer**: a generated `Board`
//! struct that names every peripheral instance and pin the plan uses,
//! destructured from embassy's `Peripherals`. It is purely *structural* — no
//! behavioral value can appear — and is the foundation the driver constructors
//! (next increment) build on. The output is a Rust source string; peri-planner
//! itself does not depend on embassy, so codegen is string generation, not
//! compilation.

use crate::pin_plan::{Placement, PinPlan};

/// Peripheral classes whose embassy singleton we bind as a `Board` field.
/// Their pins are bound regardless; analog peripherals (COMP/OPAMP) get pin
/// fields but no instance field (their instances are Tier-2/3 raw access).
const TIER1_INSTANCE_CLASSES: &[&str] =
    &["USART", "UART", "LPUART", "SPI", "I2C", "TIM", "ADC", "DAC", "FDCAN", "HRTIM"];

/// The peripheral class of an instance name, i.e. the name with its trailing
/// instance digits stripped: `"USART2" -> "USART"`, `"I2C1" -> "I2C"`,
/// `"HRTIM1" -> "HRTIM"`.
fn class_of(instance: &str) -> &str {
    instance.trim_end_matches(|c: char| c.is_ascii_digit())
}

fn is_tier1_instance(instance: &str) -> bool {
    TIER1_INSTANCE_CLASSES.contains(&class_of(instance))
}

/// Sanitize a metapac name into a snake_case Rust identifier fragment.
/// Names here are alphanumeric (`USART2`, `CH1`, `IN3`), so this just
/// lowercases; non-alphanumerics (none expected) fold to `_`.
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect()
}

/// PascalCase an instance name into a bundle struct identifier:
/// `"USART1" -> "Usart1"`, `"HRTIM1" -> "Hrtim1"`, `"I2C1" -> "I2c1"`.
fn type_name(instance: &str) -> String {
    instance
        .chars()
        .enumerate()
        .flat_map(|(i, c)| {
            if i == 0 {
                c.to_uppercase().collect::<Vec<_>>()
            } else {
                c.to_lowercase().collect::<Vec<_>>()
            }
        })
        .collect()
}

/// Generate the board-support module — one *bundle* struct per peripheral
/// instance (its typed singleton + role-named pins), aggregated into a `Board`
/// with `Board::take(p)`. We stop at this resource-grouping boundary on purpose:
/// peri-planner does NOT emit driver init, because embassy's init API churns.
/// The user constructs each peripheral from its bundle, in their own embassy
/// version's idiom. Field NAMES are stable across pin reassignment; only the pin
/// TYPES change on regenerate, and embassy constructors are generic over the
/// pin, so the user's init is unaffected. Never hand-edited.
pub fn generate_board(plan: &PinPlan) -> String {
    use std::collections::HashMap;
    use std::fmt::Write as _;

    // Group placements by peripheral instance, preserving first-seen order.
    let mut order: Vec<&str> = Vec::new();
    let mut groups: HashMap<&str, Vec<&Placement>> = HashMap::new();
    for p in &plan.placements {
        let inst = p.signal.peripheral.as_str();
        if !groups.contains_key(inst) {
            order.push(inst);
        }
        groups.entry(inst).or_default().push(p);
    }

    let mut s = String::new();
    let _ = writeln!(
        s,
        "// @generated by peri-planner from PinPlan (target {} / {}) — DO NOT EDIT.",
        plan.target.package, plan.target.family
    );
    let _ = writeln!(s, "// One bundle of typed singletons per peripheral (instance + role-named pins).");
    let _ = writeln!(s, "// peri-planner does NOT generate driver init — you construct each peripheral");
    let _ = writeln!(s, "// from its bundle, in your own embassy version's idiom. Field NAMES are stable");
    let _ = writeln!(s, "// across pin changes; only the pin TYPES change on regenerate, and embassy");
    let _ = writeln!(s, "// constructors are generic over the pin, so your init is unaffected. e.g.:");
    let _ = writeln!(s, "//   let b = Board::take(embassy_stm32::init(Default::default()));");
    let _ = writeln!(s, "//   let uart = Uart::new(b.usart1.instance, b.usart1.rx, b.usart1.tx, Irqs, dma, cfg)?;");
    let _ = writeln!(s, "#![allow(dead_code)]");
    let _ = writeln!(s);
    let _ = writeln!(s, "use embassy_stm32::{{peripherals, Peripherals}};");
    let _ = writeln!(s);

    // One bundle struct per peripheral instance.
    for inst in &order {
        let ty = type_name(inst);
        let _ = writeln!(s, "/// Resources for {inst} — pass to your own constructor.");
        let _ = writeln!(s, "pub struct {ty} {{");
        if is_tier1_instance(inst) {
            let _ = writeln!(s, "    pub instance: peripherals::{inst},");
        }
        for p in &groups[*inst] {
            match p.pin {
                Some(pin) => {
                    let _ = writeln!(s, "    pub {}: peripherals::{},", ident(&p.signal.role), pin.name());
                }
                None => {
                    let _ = writeln!(s, "    // unplaced: {} (declared, no pin yet)", p.signal.role);
                }
            }
        }
        let _ = writeln!(s, "}}");
        let _ = writeln!(s);
    }

    // Board aggregates the per-peripheral bundles.
    let _ = writeln!(s, "/// Every peripheral this design uses, grouped into per-instance bundles.");
    let _ = writeln!(s, "pub struct Board {{");
    for inst in &order {
        let _ = writeln!(s, "    pub {}: {},", ident(inst), type_name(inst));
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);

    // take(p): destructure Peripherals into the bundles.
    let _ = writeln!(s, "impl Board {{");
    let _ = writeln!(s, "    /// Destructure the embassy `Peripherals` into named per-peripheral bundles.");
    let _ = writeln!(s, "    pub fn take(p: Peripherals) -> Self {{");
    let _ = writeln!(s, "        Self {{");
    for inst in &order {
        let mut parts: Vec<String> = Vec::new();
        if is_tier1_instance(inst) {
            parts.push(format!("instance: p.{inst}"));
        }
        for p in &groups[*inst] {
            if let Some(pin) = p.pin {
                parts.push(format!("{}: p.{}", ident(&p.signal.role), pin.name()));
            }
        }
        let _ = writeln!(s, "            {}: {} {{ {} }},", ident(inst), type_name(inst), parts.join(", "));
    }
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");

    s
}

/// One behavioral parameter the pin plan cannot know — a generated `Behavior`
/// field. Adding a routed peripheral adds a hole, so the design and its config
/// can't silently drift (docs/firmware-codegen-design.md §4).
struct Hole {
    name: String,
    ty: &'static str,
    default: &'static str,
    doc: &'static str,
}

/// The behavioral holes implied by the plan's Tier-1 peripherals, in instance
/// order. Derived from the peripheral class + its placements' role kinds.
fn behavior_holes(plan: &PinPlan) -> Vec<Hole> {
    use crate::pin_plan::RoleKind;
    let mut instances: Vec<&str> = Vec::new();
    for p in &plan.placements {
        let inst = p.signal.peripheral.as_str();
        if is_tier1_instance(inst) && !instances.contains(&inst) {
            instances.push(inst);
        }
    }

    let mut holes = Vec::new();
    for inst in instances {
        let id = ident(inst);
        match class_of(inst) {
            "USART" | "UART" | "LPUART" => holes.push(Hole {
                name: format!("{id}_baud"), ty: "u32", default: "115_200", doc: "baud rate",
            }),
            "SPI" => holes.push(Hole {
                name: format!("{id}_freq_hz"), ty: "u32", default: "1_000_000", doc: "SCK frequency (Hz)",
            }),
            "I2C" => holes.push(Hole {
                name: format!("{id}_freq_hz"), ty: "u32", default: "100_000", doc: "bus frequency (Hz)",
            }),
            "FDCAN" => holes.push(Hole {
                name: format!("{id}_bitrate"), ty: "u32", default: "500_000", doc: "nominal bitrate (bps)",
            }),
            "TIM" | "HRTIM" => {
                let pwm = plan.placements.iter().any(|p| {
                    p.signal.peripheral == inst && matches!(p.role_kind, RoleKind::PwmOut { .. })
                });
                if pwm {
                    holes.push(Hole {
                        name: format!("{id}_freq_hz"), ty: "u32", default: "100_000",
                        doc: "PWM switching frequency (Hz)",
                    });
                    let dead_time = plan.placements.iter().any(|p| {
                        p.signal.peripheral == inst
                            && matches!(p.role_kind, RoleKind::PwmOut { dead_time: true, .. })
                    });
                    if dead_time {
                        holes.push(Hole {
                            name: format!("{id}_dead_time_ns"), ty: "u16", default: "0",
                            doc: "complementary dead-time (ns)",
                        });
                    }
                }
            }
            _ => {} // ADC/DAC: no required scalar in v1.
        }
    }
    holes
}

/// Append the behavioral-config contract (`Behavior` struct + `Default`) — the
/// set of holes the user fills, structurally separate from the plan.
fn write_behavior(s: &mut String, plan: &PinPlan) {
    use std::fmt::Write as _;
    let holes = behavior_holes(plan);
    let _ = writeln!(s);
    let _ = writeln!(s, "/// Behavioral configuration you must supply — one field per value the pin");
    let _ = writeln!(s, "/// plan cannot know (it carries no behavioral values by design). Adjust the");
    let _ = writeln!(s, "/// defaults to your converter. Adding a routed peripheral adds a field here,");
    let _ = writeln!(s, "/// so the design and its config can't silently drift.");
    let _ = writeln!(s, "#[derive(Clone, Copy, Debug)]");
    let _ = writeln!(s, "pub struct Behavior {{");
    for h in &holes {
        let _ = writeln!(s, "    /// {}", h.doc);
        let _ = writeln!(s, "    pub {}: {},", h.name, h.ty);
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);
    let _ = writeln!(s, "impl Default for Behavior {{");
    let _ = writeln!(s, "    fn default() -> Self {{");
    let _ = writeln!(s, "        Self {{");
    for h in &holes {
        let _ = writeln!(s, "            {}: {},", h.name, h.default);
    }
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");
}

/// Generate the full Tier-1 firmware scaffold module: the board-support layer
/// (every instance + pin) followed by the behavioral-config contract.
pub fn generate(plan: &PinPlan) -> String {
    let mut s = generate_board(plan);
    write_behavior(&mut s, plan);
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcu_pinout::{OwnedSignal, PinId};
    use crate::pin_plan::{PinOrigin, PinPlan, Placement, RoleKind, Target};

    fn placement(peripheral: &str, role: &str, pin: Option<PinId>) -> Placement {
        Placement {
            signal: OwnedSignal { peripheral: peripheral.into(), role: role.into() },
            pin,
            origin: PinOrigin::Locked,
            af: None,
            role_kind: RoleKind::Gpio,
            dma: None,
            irqs: Vec::new(),
            package_pin: None,
            net: None,
        }
    }

    #[test]
    fn generate_board_emits_per_peripheral_bundles() {
        let mut plan = PinPlan::empty(Target { package: "H523RE".into(), family: "H5".into() });
        plan.placements.push(placement("USART1", "TX", Some(PinId { port: 'A', num: 9 })));
        plan.placements.push(placement("USART1", "RX", None)); // declared, unplaced
        let code = generate_board(&plan);

        assert!(code.contains("from PinPlan (target H523RE / H5)"));
        // A per-peripheral bundle struct with instance + role-named pin fields.
        assert!(code.contains("pub struct Usart1 {"));
        assert!(code.contains("    pub instance: peripherals::USART1,"));
        assert!(code.contains("    pub tx: peripherals::PA9,"));
        // Board aggregates the bundle; take() builds it from `p`.
        assert!(code.contains("    pub usart1: Usart1,"));
        assert!(code.contains("usart1: Usart1 { instance: p.USART1, tx: p.PA9 },"));
        // Unplaced signal -> comment inside the bundle, never a bogus field.
        assert!(code.contains("// unplaced: RX"));
        assert!(!code.contains("pub rx: peripherals::"));
    }

    #[test]
    fn analog_peripherals_bundle_pins_but_not_instance() {
        // COMP is not a Tier-1 instance class: its pins are bundled, instance is not.
        let mut plan = PinPlan::empty(Target { package: "G474R".into(), family: "G4".into() });
        plan.placements.push(placement("COMP1", "INP", Some(PinId { port: 'A', num: 1 })));
        plan.placements.push(placement("ADC1", "IN2", Some(PinId { port: 'A', num: 2 })));
        let code = generate_board(&plan);

        assert!(code.contains("pub struct Comp1 {"));
        assert!(code.contains("    pub inp: peripherals::PA1,"), "COMP pin bundled");
        assert!(!code.contains("pub instance: peripherals::COMP1,"), "COMP instance NOT bound (Tier-2/3)");
        assert!(code.contains("pub struct Adc1 {"));
        assert!(code.contains("    pub instance: peripherals::ADC1,"), "ADC instance bound (Tier-1)");
        assert!(code.contains("    pub in2: peripherals::PA2,"));
    }

    #[test]
    fn generate_emits_behavior_contract_holes() {
        let mut plan = PinPlan::empty(Target { package: "G474R".into(), family: "G4".into() });
        plan.placements.push(placement("USART1", "TX", Some(PinId { port: 'A', num: 9 })));
        plan.placements.push(placement("SPI1", "SCK", Some(PinId { port: 'A', num: 5 })));
        // A complementary PWM channel with dead-time -> freq + dead-time holes.
        plan.placements.push(Placement {
            role_kind: RoleKind::PwmOut { complementary: true, dead_time: true, etr: false },
            ..placement("TIM1", "CH1", Some(PinId { port: 'A', num: 8 }))
        });
        let code = generate(&plan);

        // One hole per behavioral value the plan can't know.
        assert!(code.contains("pub usart1_baud: u32,"));
        assert!(code.contains("pub spi1_freq_hz: u32,"));
        assert!(code.contains("pub tim1_freq_hz: u32,"));
        assert!(code.contains("pub tim1_dead_time_ns: u16,"));
        // Defaults wired up.
        assert!(code.contains("usart1_baud: 115_200,"));
        assert!(code.contains("tim1_dead_time_ns: 0,"));
        // Behavior struct present; board layer still emitted above it.
        assert!(code.contains("pub struct Behavior {"));
        assert!(code.contains("pub struct Board {"));
        // No behavioral VALUE ever leaks into the board layer.
        assert!(!code.contains("115_200,\n    pub usart1: peripherals"));
    }

    #[test]
    fn class_of_strips_instance_digits() {
        assert_eq!(class_of("USART2"), "USART");
        assert_eq!(class_of("I2C1"), "I2C");
        assert_eq!(class_of("HRTIM1"), "HRTIM");
        assert!(is_tier1_instance("LPUART1"));
        assert!(!is_tier1_instance("COMP1"));
    }
}
