// GENERATED by `gen_fabric` from cubedb CubeMX IP "modes" XML + RM0440 — do not edit by hand.

/// DAC channel -> comparator inverting input, as `(dac_instance,
/// dac_channel, comp_instance)`. From CubeMX COMP `InvertingInput`
/// modes (`$IpNumber` instance gating). Family-level (G4). Validated
/// against the hand-coded `G474_EDGES`.
pub static G4_DAC_TO_COMP: &[(u8, u8, u8)] = &[
    (1, 1, 1),
    (1, 1, 3),
    (1, 1, 4),
    (1, 2, 2),
    (1, 2, 5),
    (2, 1, 6),
    (2, 1, 7),
    (3, 1, 1),
    (3, 1, 3),
    (3, 2, 2),
    (3, 2, 4),
    (4, 1, 5),
    (4, 1, 7),
    (4, 2, 6),
];

/// Comparator output -> HRTIM external event, as `(comp_instance,
/// eev_number)`. From CubeMX HRTIM `HRTIM_EEV<n>SRC_COMP<c>_OUT`
/// modes, plus documented fixups for cubedb bugs (see gen_fabric).
/// Validated against the hand-coded `COMP_TO_EEV`.
pub static G4_COMP_TO_EEV: &[(u8, u8)] = &[
    (1, 4),
    (1, 6),
    (2, 1),
    (2, 6),
    (3, 5),
    (3, 8),
    (4, 2),
    (4, 7),
    (4, 9),
    (5, 4),
    (5, 9),
    (6, 3),
    (6, 8),
    (7, 5),
    (7, 10),
];

/// Comparator output -> HRTIM fault input, as `(comp_instance,
/// flt_number)`. NOT in cubedb (which only abstracts faults to a
/// source type); parsed from RM0440 "Table 228. Fault inputs".
/// COMP7 has no fault input. Validated against the hand `COMP_TO_FLT`.
pub static G4_COMP_TO_FLT: &[(u8, u8)] = &[
    (1, 4),
    (2, 1),
    (3, 5),
    (4, 2),
    (5, 6),
    (6, 3),
];

/// HRTIM crossbar source -> ADC trigger, as `(CrossbarSource Debug
/// name, &[adc-trigger numbers])`. From CubeMX HRTIM
/// ADCTRIGGEREVENT{13|24} modes (13->{1,3}, 24->{2,4}), with
/// RM0440-verified fixups. Validated against `CROSSBAR_TO_ADC_TRIGGER`.
pub static G4_CROSSBAR_TO_ADC_TRIGGER: &[(&str, &[u8])] = &[
    ("Eev1", &[1, 3]),
    ("Eev10", &[2, 4]),
    ("Eev2", &[1, 3]),
    ("Eev3", &[1, 3]),
    ("Eev4", &[1, 3]),
    ("Eev5", &[1, 3]),
    ("Eev6", &[2, 4]),
    ("Eev7", &[2, 4]),
    ("Eev8", &[2, 4]),
    ("Eev9", &[2, 4]),
    ("Mcr1", &[1, 2, 3, 4]),
    ("Mcr2", &[1, 2, 3, 4]),
    ("Mcr3", &[1, 2, 3, 4]),
    ("Mcr4", &[1, 2, 3, 4]),
    ("Mper", &[1, 2, 3, 4]),
    ("TimACr2", &[2, 4]),
    ("TimACr3", &[1, 3]),
    ("TimACr4", &[1, 2, 3, 4]),
    ("TimACrPer", &[1, 2, 3, 4]),
    ("TimACrRst", &[1, 3]),
    ("TimBCr2", &[2, 4]),
    ("TimBCr3", &[1, 3]),
    ("TimBCr4", &[1, 2, 3, 4]),
    ("TimBCrPer", &[1, 2, 3, 4]),
    ("TimBCrRst", &[1, 3]),
    ("TimCCr2", &[2, 4]),
    ("TimCCr3", &[1, 3]),
    ("TimCCr4", &[1, 2, 3, 4]),
    ("TimCCrPer", &[1, 2, 3, 4]),
    ("TimCCrRst", &[2, 4]),
    ("TimDCr2", &[2, 4]),
    ("TimDCr3", &[1, 3]),
    ("TimDCr4", &[1, 2, 3, 4]),
    ("TimDCrPer", &[1, 2, 3, 4]),
    ("TimDCrRst", &[2, 4]),
    ("TimECr2", &[2, 4]),
    ("TimECr3", &[1, 2, 3, 4]),
    ("TimECr4", &[1, 2, 3, 4]),
    ("TimECrPer", &[1, 3]),
    ("TimECrRst", &[2, 4]),
    ("TimFCr2", &[2, 4]),
    ("TimFCr3", &[1, 2, 3, 4]),
    ("TimFCr4", &[1, 2, 3, 4]),
    ("TimFCrPer", &[1, 2, 3, 4]),
    ("TimFCrRst", &[1, 3]),
];
